# marketplaced — the Cosmos SDK chain binary (cmd/marketplaced). Builds and
# runs the node itself; it does NOT generate genesis or validator keys on
# start (see scripts/start_blockchain.sh for that one-time init flow) —
# those come from a --home volume provisioned ahead of time, the same way
# any real validator's key material is provisioned out-of-band rather than
# baked into or generated by the container.
FROM golang:1.24-alpine AS build
RUN apk add --no-cache git gcc musl-dev linux-headers
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=1 go build -trimpath -ldflags="-s -w" -o /out/marketplaced ./cmd/marketplaced

FROM alpine:3.19
RUN apk add --no-cache ca-certificates wget && \
    addgroup -g 1001 -S marketplaced && adduser -S marketplaced -u 1001
WORKDIR /home/marketplaced
COPY --from=build /out/marketplaced /usr/local/bin/marketplaced
RUN mkdir -p /home/marketplaced/.marketplaced && chown -R marketplaced:marketplaced /home/marketplaced
USER marketplaced
ENV HOME=/home/marketplaced

EXPOSE 26656 26657 1317 9090
HEALTHCHECK --interval=30s --timeout=3s --start-period=30s --retries=3 \
  CMD wget -qO- http://127.0.0.1:26657/status || exit 1

ENTRYPOINT ["marketplaced"]
CMD ["start", "--home=/home/marketplaced/.marketplaced", "--minimum-gas-prices=0.01umal", "--rpc.laddr=tcp://0.0.0.0:26657", "--api.enable", "--api.address=tcp://0.0.0.0:1317"]
