// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: marketplace/mallcoin/v1/query.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_marketplace_mallcoin_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mallcoin_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_marketplace_mallcoin_v1_query_proto_rawDescGZIP(), []int{0}
}

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// params holds all the parameters of this module.
	Params        *Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_marketplace_mallcoin_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mallcoin_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_mallcoin_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

var File_marketplace_mallcoin_v1_query_proto protoreflect.FileDescriptor

const file_marketplace_mallcoin_v1_query_proto_rawDesc = "" +
	"\n" +
	"#marketplace/mallcoin/v1/query.proto\x12\x17marketplace.mallcoin.v1\x1a\x11amino/amino.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\x1a$marketplace/mallcoin/v1/params.proto\"\x14\n" +
	"\x12QueryParamsRequest\"Y\n" +
	"\x13QueryParamsResponse\x12B\n" +
	"\x06params\x18\x01 \x01(\v2\x1f.marketplace.mallcoin.v1.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params2\x9a\x01\n" +
	"\x05Query\x12\x90\x01\n" +
	"\x06Params\x12+.marketplace.mallcoin.v1.QueryParamsRequest\x1a,.marketplace.mallcoin.v1.QueryParamsResponse\"+\x82\xd3\xe4\x93\x02%\x12#/tmp/marketplace/mallcoin/v1/paramsB-Z+github.com/tmp/marketplace/x/mallcoin/typesb\x06proto3"

var (
	file_marketplace_mallcoin_v1_query_proto_rawDescOnce sync.Once
	file_marketplace_mallcoin_v1_query_proto_rawDescData []byte
)

func file_marketplace_mallcoin_v1_query_proto_rawDescGZIP() []byte {
	file_marketplace_mallcoin_v1_query_proto_rawDescOnce.Do(func() {
		file_marketplace_mallcoin_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketplace_mallcoin_v1_query_proto_rawDesc), len(file_marketplace_mallcoin_v1_query_proto_rawDesc)))
	})
	return file_marketplace_mallcoin_v1_query_proto_rawDescData
}

var file_marketplace_mallcoin_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_marketplace_mallcoin_v1_query_proto_goTypes = []any{
	(*QueryParamsRequest)(nil),  // 0: marketplace.mallcoin.v1.QueryParamsRequest
	(*QueryParamsResponse)(nil), // 1: marketplace.mallcoin.v1.QueryParamsResponse
	(*Params)(nil),              // 2: marketplace.mallcoin.v1.Params
}
var file_marketplace_mallcoin_v1_query_proto_depIdxs = []int32{
	2, // 0: marketplace.mallcoin.v1.QueryParamsResponse.params:type_name -> marketplace.mallcoin.v1.Params
	0, // 1: marketplace.mallcoin.v1.Query.Params:input_type -> marketplace.mallcoin.v1.QueryParamsRequest
	1, // 2: marketplace.mallcoin.v1.Query.Params:output_type -> marketplace.mallcoin.v1.QueryParamsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_marketplace_mallcoin_v1_query_proto_init() }
func file_marketplace_mallcoin_v1_query_proto_init() {
	if File_marketplace_mallcoin_v1_query_proto != nil {
		return
	}
	file_marketplace_mallcoin_v1_params_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketplace_mallcoin_v1_query_proto_rawDesc), len(file_marketplace_mallcoin_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marketplace_mallcoin_v1_query_proto_goTypes,
		DependencyIndexes: file_marketplace_mallcoin_v1_query_proto_depIdxs,
		MessageInfos:      file_marketplace_mallcoin_v1_query_proto_msgTypes,
	}.Build()
	File_marketplace_mallcoin_v1_query_proto = out.File
	file_marketplace_mallcoin_v1_query_proto_goTypes = nil
	file_marketplace_mallcoin_v1_query_proto_depIdxs = nil
}
