// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: marketplace/mallcoin/v1/tx.proto

package types

import (
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// params defines the module parameters to update.
	//
	// NOTE: All parameters must be supplied.
	Params        *Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParams) Reset() {
	*x = MsgUpdateParams{}
	mi := &file_marketplace_mallcoin_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParams) ProtoMessage() {}

func (x *MsgUpdateParams) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mallcoin_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParams.ProtoReflect.Descriptor instead.
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return file_marketplace_mallcoin_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgUpdateParams) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgUpdateParams) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParamsResponse) Reset() {
	*x = MsgUpdateParamsResponse{}
	mi := &file_marketplace_mallcoin_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParamsResponse) ProtoMessage() {}

func (x *MsgUpdateParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mallcoin_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParamsResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_mallcoin_v1_tx_proto_rawDescGZIP(), []int{1}
}

var File_marketplace_mallcoin_v1_tx_proto protoreflect.FileDescriptor

const file_marketplace_mallcoin_v1_tx_proto_rawDesc = "" +
	"\n" +
	" marketplace/mallcoin/v1/tx.proto\x12\x17marketplace.mallcoin.v1\x1a\x11amino/amino.proto\x1a\x17cosmos/msg/v1/msg.proto\x1a\x19cosmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\x1a$marketplace/mallcoin/v1/params.proto\"\xc8\x01\n" +
	"\x0fMsgUpdateParams\x126\n" +
	"\tauthority\x18\x01 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\tauthority\x12B\n" +
	"\x06params\x18\x02 \x01(\v2\x1f.marketplace.mallcoin.v1.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params:9\x82\xe7\xb0*\tauthority\x8a\xe7\xb0*&marketplace/x/mallcoin/MsgUpdateParams\"\x19\n" +
	"\x17MsgUpdateParamsResponse2x\n" +
	"\x03Msg\x12j\n" +
	"\fUpdateParams\x12(.marketplace.mallcoin.v1.MsgUpdateParams\x1a0.marketplace.mallcoin.v1.MsgUpdateParamsResponse\x1a\x05\x80\xe7\xb0*\x01B-Z+github.com/tmp/marketplace/x/mallcoin/typesb\x06proto3"

var (
	file_marketplace_mallcoin_v1_tx_proto_rawDescOnce sync.Once
	file_marketplace_mallcoin_v1_tx_proto_rawDescData []byte
)

func file_marketplace_mallcoin_v1_tx_proto_rawDescGZIP() []byte {
	file_marketplace_mallcoin_v1_tx_proto_rawDescOnce.Do(func() {
		file_marketplace_mallcoin_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketplace_mallcoin_v1_tx_proto_rawDesc), len(file_marketplace_mallcoin_v1_tx_proto_rawDesc)))
	})
	return file_marketplace_mallcoin_v1_tx_proto_rawDescData
}

var file_marketplace_mallcoin_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_marketplace_mallcoin_v1_tx_proto_goTypes = []any{
	(*MsgUpdateParams)(nil),         // 0: marketplace.mallcoin.v1.MsgUpdateParams
	(*MsgUpdateParamsResponse)(nil), // 1: marketplace.mallcoin.v1.MsgUpdateParamsResponse
	(*Params)(nil),                  // 2: marketplace.mallcoin.v1.Params
}
var file_marketplace_mallcoin_v1_tx_proto_depIdxs = []int32{
	2, // 0: marketplace.mallcoin.v1.MsgUpdateParams.params:type_name -> marketplace.mallcoin.v1.Params
	0, // 1: marketplace.mallcoin.v1.Msg.UpdateParams:input_type -> marketplace.mallcoin.v1.MsgUpdateParams
	1, // 2: marketplace.mallcoin.v1.Msg.UpdateParams:output_type -> marketplace.mallcoin.v1.MsgUpdateParamsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_marketplace_mallcoin_v1_tx_proto_init() }
func file_marketplace_mallcoin_v1_tx_proto_init() {
	if File_marketplace_mallcoin_v1_tx_proto != nil {
		return
	}
	file_marketplace_mallcoin_v1_params_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketplace_mallcoin_v1_tx_proto_rawDesc), len(file_marketplace_mallcoin_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marketplace_mallcoin_v1_tx_proto_goTypes,
		DependencyIndexes: file_marketplace_mallcoin_v1_tx_proto_depIdxs,
		MessageInfos:      file_marketplace_mallcoin_v1_tx_proto_msgTypes,
	}.Build()
	File_marketplace_mallcoin_v1_tx_proto = out.File
	file_marketplace_mallcoin_v1_tx_proto_goTypes = nil
	file_marketplace_mallcoin_v1_tx_proto_depIdxs = nil
}
