// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: marketplace/crosschain/v1/query.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_BridgeTransfer_FullMethodName  = "/marketplace.crosschain.v1.Query/BridgeTransfer"
	Query_BridgeTransfers_FullMethodName = "/marketplace.crosschain.v1.Query/BridgeTransfers"
	Query_BridgeState_FullMethodName     = "/marketplace.crosschain.v1.Query/BridgeState"
	Query_Params_FullMethodName          = "/marketplace.crosschain.v1.Query/Params"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query defines the gRPC querier service.
type QueryClient interface {
	// BridgeTransfer queries a specific bridge transfer by ID.
	BridgeTransfer(ctx context.Context, in *QueryBridgeTransferRequest, opts ...grpc.CallOption) (*QueryBridgeTransferResponse, error)
	// BridgeTransfers queries all bridge transfers with pagination.
	BridgeTransfers(ctx context.Context, in *QueryBridgeTransfersRequest, opts ...grpc.CallOption) (*QueryBridgeTransfersResponse, error)
	// BridgeState queries the current bridge state.
	BridgeState(ctx context.Context, in *QueryBridgeStateRequest, opts ...grpc.CallOption) (*QueryBridgeStateResponse, error)
	// Params queries all parameters of the crosschain module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) BridgeTransfer(ctx context.Context, in *QueryBridgeTransferRequest, opts ...grpc.CallOption) (*QueryBridgeTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryBridgeTransferResponse)
	err := c.cc.Invoke(ctx, Query_BridgeTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BridgeTransfers(ctx context.Context, in *QueryBridgeTransfersRequest, opts ...grpc.CallOption) (*QueryBridgeTransfersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryBridgeTransfersResponse)
	err := c.cc.Invoke(ctx, Query_BridgeTransfers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BridgeState(ctx context.Context, in *QueryBridgeStateRequest, opts ...grpc.CallOption) (*QueryBridgeStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryBridgeStateResponse)
	err := c.cc.Invoke(ctx, Query_BridgeState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query defines the gRPC querier service.
type QueryServer interface {
	// BridgeTransfer queries a specific bridge transfer by ID.
	BridgeTransfer(context.Context, *QueryBridgeTransferRequest) (*QueryBridgeTransferResponse, error)
	// BridgeTransfers queries all bridge transfers with pagination.
	BridgeTransfers(context.Context, *QueryBridgeTransfersRequest) (*QueryBridgeTransfersResponse, error)
	// BridgeState queries the current bridge state.
	BridgeState(context.Context, *QueryBridgeStateRequest) (*QueryBridgeStateResponse, error)
	// Params queries all parameters of the crosschain module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) BridgeTransfer(context.Context, *QueryBridgeTransferRequest) (*QueryBridgeTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BridgeTransfer not implemented")
}
func (UnimplementedQueryServer) BridgeTransfers(context.Context, *QueryBridgeTransfersRequest) (*QueryBridgeTransfersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BridgeTransfers not implemented")
}
func (UnimplementedQueryServer) BridgeState(context.Context, *QueryBridgeStateRequest) (*QueryBridgeStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BridgeState not implemented")
}
func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call panics, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_BridgeTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBridgeTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BridgeTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_BridgeTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BridgeTransfer(ctx, req.(*QueryBridgeTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BridgeTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBridgeTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BridgeTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_BridgeTransfers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BridgeTransfers(ctx, req.(*QueryBridgeTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BridgeState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBridgeStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BridgeState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_BridgeState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BridgeState(ctx, req.(*QueryBridgeStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marketplace.crosschain.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BridgeTransfer",
			Handler:    _Query_BridgeTransfer_Handler,
		},
		{
			MethodName: "BridgeTransfers",
			Handler:    _Query_BridgeTransfers_Handler,
		},
		{
			MethodName: "BridgeState",
			Handler:    _Query_BridgeState_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "marketplace/crosschain/v1/query.proto",
}
