// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: marketplace/mallpoints/v1/query.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_Params_FullMethodName              = "/marketplace.mallpoints.v1.Query/Params"
	Query_GetUserPoints_FullMethodName       = "/marketplace.mallpoints.v1.Query/GetUserPoints"
	Query_ListUserPoints_FullMethodName      = "/marketplace.mallpoints.v1.Query/ListUserPoints"
	Query_GetConversionWindow_FullMethodName = "/marketplace.mallpoints.v1.Query/GetConversionWindow"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query defines the gRPC querier service.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// ListUserPoints Queries a list of UserPoints items.
	GetUserPoints(ctx context.Context, in *QueryGetUserPointsRequest, opts ...grpc.CallOption) (*QueryGetUserPointsResponse, error)
	// ListUserPoints defines the ListUserPoints RPC.
	ListUserPoints(ctx context.Context, in *QueryAllUserPointsRequest, opts ...grpc.CallOption) (*QueryAllUserPointsResponse, error)
	// Queries a ConversionWindow by index.
	GetConversionWindow(ctx context.Context, in *QueryGetConversionWindowRequest, opts ...grpc.CallOption) (*QueryGetConversionWindowResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetUserPoints(ctx context.Context, in *QueryGetUserPointsRequest, opts ...grpc.CallOption) (*QueryGetUserPointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetUserPointsResponse)
	err := c.cc.Invoke(ctx, Query_GetUserPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListUserPoints(ctx context.Context, in *QueryAllUserPointsRequest, opts ...grpc.CallOption) (*QueryAllUserPointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryAllUserPointsResponse)
	err := c.cc.Invoke(ctx, Query_ListUserPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetConversionWindow(ctx context.Context, in *QueryGetConversionWindowRequest, opts ...grpc.CallOption) (*QueryGetConversionWindowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGetConversionWindowResponse)
	err := c.cc.Invoke(ctx, Query_GetConversionWindow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query defines the gRPC querier service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// ListUserPoints Queries a list of UserPoints items.
	GetUserPoints(context.Context, *QueryGetUserPointsRequest) (*QueryGetUserPointsResponse, error)
	// ListUserPoints defines the ListUserPoints RPC.
	ListUserPoints(context.Context, *QueryAllUserPointsRequest) (*QueryAllUserPointsResponse, error)
	// Queries a ConversionWindow by index.
	GetConversionWindow(context.Context, *QueryGetConversionWindowRequest) (*QueryGetConversionWindowResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) GetUserPoints(context.Context, *QueryGetUserPointsRequest) (*QueryGetUserPointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserPoints not implemented")
}
func (UnimplementedQueryServer) ListUserPoints(context.Context, *QueryAllUserPointsRequest) (*QueryAllUserPointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserPoints not implemented")
}
func (UnimplementedQueryServer) GetConversionWindow(context.Context, *QueryGetConversionWindowRequest) (*QueryGetConversionWindowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConversionWindow not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call panics, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetUserPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetUserPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetUserPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetUserPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetUserPoints(ctx, req.(*QueryGetUserPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListUserPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllUserPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListUserPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListUserPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListUserPoints(ctx, req.(*QueryAllUserPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetConversionWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetConversionWindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetConversionWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetConversionWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetConversionWindow(ctx, req.(*QueryGetConversionWindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marketplace.mallpoints.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetUserPoints",
			Handler:    _Query_GetUserPoints_Handler,
		},
		{
			MethodName: "ListUserPoints",
			Handler:    _Query_ListUserPoints_Handler,
		},
		{
			MethodName: "GetConversionWindow",
			Handler:    _Query_GetConversionWindow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "marketplace/mallpoints/v1/query.proto",
}
