// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: marketplace/marketplace/v1/query.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgGetEscrow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EscrowId      string                 `protobuf:"bytes,1,opt,name=escrow_id,json=escrowId,proto3" json:"escrow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgGetEscrow) Reset() {
	*x = MsgGetEscrow{}
	mi := &file_marketplace_marketplace_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgGetEscrow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetEscrow) ProtoMessage() {}

func (x *MsgGetEscrow) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_marketplace_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetEscrow.ProtoReflect.Descriptor instead.
func (*MsgGetEscrow) Descriptor() ([]byte, []int) {
	return file_marketplace_marketplace_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *MsgGetEscrow) GetEscrowId() string {
	if x != nil {
		return x.EscrowId
	}
	return ""
}

type MsgGetEscrowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Buyer         string                 `protobuf:"bytes,2,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Seller        string                 `protobuf:"bytes,3,opt,name=seller,proto3" json:"seller,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Denom         string                 `protobuf:"bytes,5,opt,name=denom,proto3" json:"denom,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ReleaseTime   int64                  `protobuf:"varint,9,opt,name=release_time,json=releaseTime,proto3" json:"release_time,omitempty"`
	DisputeWindow int64                  `protobuf:"varint,10,opt,name=dispute_window,json=disputeWindow,proto3" json:"dispute_window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgGetEscrowResponse) Reset() {
	*x = MsgGetEscrowResponse{}
	mi := &file_marketplace_marketplace_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgGetEscrowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetEscrowResponse) ProtoMessage() {}

func (x *MsgGetEscrowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_marketplace_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetEscrowResponse.ProtoReflect.Descriptor instead.
func (*MsgGetEscrowResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_marketplace_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *MsgGetEscrowResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MsgGetEscrowResponse) GetBuyer() string {
	if x != nil {
		return x.Buyer
	}
	return ""
}

func (x *MsgGetEscrowResponse) GetSeller() string {
	if x != nil {
		return x.Seller
	}
	return ""
}

func (x *MsgGetEscrowResponse) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *MsgGetEscrowResponse) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *MsgGetEscrowResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MsgGetEscrowResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MsgGetEscrowResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *MsgGetEscrowResponse) GetReleaseTime() int64 {
	if x != nil {
		return x.ReleaseTime
	}
	return 0
}

func (x *MsgGetEscrowResponse) GetDisputeWindow() int64 {
	if x != nil {
		return x.DisputeWindow
	}
	return 0
}

type MsgListEscrows struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgListEscrows) Reset() {
	*x = MsgListEscrows{}
	mi := &file_marketplace_marketplace_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgListEscrows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgListEscrows) ProtoMessage() {}

func (x *MsgListEscrows) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_marketplace_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgListEscrows.ProtoReflect.Descriptor instead.
func (*MsgListEscrows) Descriptor() ([]byte, []int) {
	return file_marketplace_marketplace_v1_query_proto_rawDescGZIP(), []int{2}
}

type MsgListEscrowsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Escrows       []*MsgGetEscrowResponse `protobuf:"bytes,1,rep,name=escrows,proto3" json:"escrows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgListEscrowsResponse) Reset() {
	*x = MsgListEscrowsResponse{}
	mi := &file_marketplace_marketplace_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgListEscrowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgListEscrowsResponse) ProtoMessage() {}

func (x *MsgListEscrowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_marketplace_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgListEscrowsResponse.ProtoReflect.Descriptor instead.
func (*MsgListEscrowsResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_marketplace_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *MsgListEscrowsResponse) GetEscrows() []*MsgGetEscrowResponse {
	if x != nil {
		return x.Escrows
	}
	return nil
}

var File_marketplace_marketplace_v1_query_proto protoreflect.FileDescriptor

const file_marketplace_marketplace_v1_query_proto_rawDesc = "" +
	"\n" +
	"&marketplace/marketplace/v1/query.proto\x12\x1amarketplace.marketplace.v1\"+\n" +
	"\fMsgGetEscrow\x12\x1b\n" +
	"\tescrow_id\x18\x01 \x01(\tR\bescrowId\"\xa5\x02\n" +
	"\x14MsgGetEscrowResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05buyer\x18\x02 \x01(\tR\x05buyer\x12\x16\n" +
	"\x06seller\x18\x03 \x01(\tR\x06seller\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x14\n" +
	"\x05denom\x18\x05 \x01(\tR\x05denom\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12!\n" +
	"\frelease_time\x18\t \x01(\x03R\vreleaseTime\x12%\n" +
	"\x0edispute_window\x18\n" +
	" \x01(\x03R\rdisputeWindow\"\x10\n" +
	"\x0eMsgListEscrows\"d\n" +
	"\x16MsgListEscrowsResponse\x12J\n" +
	"\aescrows\x18\x01 \x03(\v20.marketplace.marketplace.v1.MsgGetEscrowResponseR\aescrowsB!Z\x1fmarketplace/x/marketplace/typesb\x06proto3"

var (
	file_marketplace_marketplace_v1_query_proto_rawDescOnce sync.Once
	file_marketplace_marketplace_v1_query_proto_rawDescData []byte
)

func file_marketplace_marketplace_v1_query_proto_rawDescGZIP() []byte {
	file_marketplace_marketplace_v1_query_proto_rawDescOnce.Do(func() {
		file_marketplace_marketplace_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketplace_marketplace_v1_query_proto_rawDesc), len(file_marketplace_marketplace_v1_query_proto_rawDesc)))
	})
	return file_marketplace_marketplace_v1_query_proto_rawDescData
}

var file_marketplace_marketplace_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_marketplace_marketplace_v1_query_proto_goTypes = []any{
	(*MsgGetEscrow)(nil),           // 0: marketplace.marketplace.v1.MsgGetEscrow
	(*MsgGetEscrowResponse)(nil),   // 1: marketplace.marketplace.v1.MsgGetEscrowResponse
	(*MsgListEscrows)(nil),         // 2: marketplace.marketplace.v1.MsgListEscrows
	(*MsgListEscrowsResponse)(nil), // 3: marketplace.marketplace.v1.MsgListEscrowsResponse
}
var file_marketplace_marketplace_v1_query_proto_depIdxs = []int32{
	1, // 0: marketplace.marketplace.v1.MsgListEscrowsResponse.escrows:type_name -> marketplace.marketplace.v1.MsgGetEscrowResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_marketplace_marketplace_v1_query_proto_init() }
func file_marketplace_marketplace_v1_query_proto_init() {
	if File_marketplace_marketplace_v1_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketplace_marketplace_v1_query_proto_rawDesc), len(file_marketplace_marketplace_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_marketplace_marketplace_v1_query_proto_goTypes,
		DependencyIndexes: file_marketplace_marketplace_v1_query_proto_depIdxs,
		MessageInfos:      file_marketplace_marketplace_v1_query_proto_msgTypes,
	}.Build()
	File_marketplace_marketplace_v1_query_proto = out.File
	file_marketplace_marketplace_v1_query_proto_goTypes = nil
	file_marketplace_marketplace_v1_query_proto_depIdxs = nil
}
