syntax = "proto3";

package marketplace.marketplace.v1;

option go_package = "marketplace/x/marketplace/types";

import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "marketplace/marketplace/v1/tx.proto";

// Query defines the gRPC querier service for the marketplace module.
service Query {
  // Escrow queries a single escrow by id.
  rpc Escrow(QueryEscrowRequest) returns (QueryEscrowResponse) {
    option (google.api.http).get = "/marketplace/marketplace/v1/escrow/{escrow_id}";
  }

  // Escrows queries all escrows.
  rpc Escrows(QueryEscrowsRequest) returns (QueryEscrowsResponse) {
    option (google.api.http).get = "/marketplace/marketplace/v1/escrow";
  }
}

message QueryEscrowRequest {
  string escrow_id = 1;
}

message QueryEscrowResponse {
  Escrow escrow = 1 [(gogoproto.nullable) = false];
}

message QueryEscrowsRequest {}

message QueryEscrowsResponse {
  repeated Escrow escrows = 1 [(gogoproto.nullable) = false];
}
