// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: marketplace/mallpoints/v1/query.proto

package types

import (
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_marketplace_mallpoints_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mallpoints_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_marketplace_mallpoints_v1_query_proto_rawDescGZIP(), []int{0}
}

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// params holds all the parameters of this module.
	Params        *Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_marketplace_mallpoints_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mallpoints_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_mallpoints_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

// QueryGetUserPointsRequest defines the QueryGetUserPointsRequest message.
type QueryGetUserPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         string                 `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGetUserPointsRequest) Reset() {
	*x = QueryGetUserPointsRequest{}
	mi := &file_marketplace_mallpoints_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGetUserPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGetUserPointsRequest) ProtoMessage() {}

func (x *QueryGetUserPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mallpoints_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGetUserPointsRequest.ProtoReflect.Descriptor instead.
func (*QueryGetUserPointsRequest) Descriptor() ([]byte, []int) {
	return file_marketplace_mallpoints_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryGetUserPointsRequest) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

// QueryGetUserPointsResponse defines the QueryGetUserPointsResponse message.
type QueryGetUserPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserPoints    *UserPoints            `protobuf:"bytes,1,opt,name=user_points,json=userPoints,proto3" json:"user_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGetUserPointsResponse) Reset() {
	*x = QueryGetUserPointsResponse{}
	mi := &file_marketplace_mallpoints_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGetUserPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGetUserPointsResponse) ProtoMessage() {}

func (x *QueryGetUserPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mallpoints_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGetUserPointsResponse.ProtoReflect.Descriptor instead.
func (*QueryGetUserPointsResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_mallpoints_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryGetUserPointsResponse) GetUserPoints() *UserPoints {
	if x != nil {
		return x.UserPoints
	}
	return nil
}

// QueryAllUserPointsRequest defines the QueryAllUserPointsRequest message.
type QueryAllUserPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *query.PageRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAllUserPointsRequest) Reset() {
	*x = QueryAllUserPointsRequest{}
	mi := &file_marketplace_mallpoints_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAllUserPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAllUserPointsRequest) ProtoMessage() {}

func (x *QueryAllUserPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mallpoints_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAllUserPointsRequest.ProtoReflect.Descriptor instead.
func (*QueryAllUserPointsRequest) Descriptor() ([]byte, []int) {
	return file_marketplace_mallpoints_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryAllUserPointsRequest) GetPagination() *query.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// QueryAllUserPointsResponse defines the QueryAllUserPointsResponse message.
type QueryAllUserPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserPoints    []*UserPoints          `protobuf:"bytes,1,rep,name=user_points,json=userPoints,proto3" json:"user_points,omitempty"`
	Pagination    *query.PageResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAllUserPointsResponse) Reset() {
	*x = QueryAllUserPointsResponse{}
	mi := &file_marketplace_mallpoints_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAllUserPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAllUserPointsResponse) ProtoMessage() {}

func (x *QueryAllUserPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mallpoints_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAllUserPointsResponse.ProtoReflect.Descriptor instead.
func (*QueryAllUserPointsResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_mallpoints_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryAllUserPointsResponse) GetUserPoints() []*UserPoints {
	if x != nil {
		return x.UserPoints
	}
	return nil
}

func (x *QueryAllUserPointsResponse) GetPagination() *query.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// QueryGetConversionWindowRequest defines the QueryGetConversionWindowRequest message.
type QueryGetConversionWindowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGetConversionWindowRequest) Reset() {
	*x = QueryGetConversionWindowRequest{}
	mi := &file_marketplace_mallpoints_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGetConversionWindowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGetConversionWindowRequest) ProtoMessage() {}

func (x *QueryGetConversionWindowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mallpoints_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGetConversionWindowRequest.ProtoReflect.Descriptor instead.
func (*QueryGetConversionWindowRequest) Descriptor() ([]byte, []int) {
	return file_marketplace_mallpoints_v1_query_proto_rawDescGZIP(), []int{6}
}

// QueryGetConversionWindowResponse defines the QueryGetConversionWindowResponse message.
type QueryGetConversionWindowResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConversionWindow *ConversionWindow      `protobuf:"bytes,1,opt,name=conversion_window,json=conversionWindow,proto3" json:"conversion_window,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueryGetConversionWindowResponse) Reset() {
	*x = QueryGetConversionWindowResponse{}
	mi := &file_marketplace_mallpoints_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGetConversionWindowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGetConversionWindowResponse) ProtoMessage() {}

func (x *QueryGetConversionWindowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mallpoints_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGetConversionWindowResponse.ProtoReflect.Descriptor instead.
func (*QueryGetConversionWindowResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_mallpoints_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *QueryGetConversionWindowResponse) GetConversionWindow() *ConversionWindow {
	if x != nil {
		return x.ConversionWindow
	}
	return nil
}

var File_marketplace_mallpoints_v1_query_proto protoreflect.FileDescriptor

const file_marketplace_mallpoints_v1_query_proto_rawDesc = "" +
	"\n" +
	"%marketplace/mallpoints/v1/query.proto\x12\x19marketplace.mallpoints.v1\x1a\x11amino/amino.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\x1a1marketplace/mallpoints/v1/conversion_window.proto\x1a&marketplace/mallpoints/v1/params.proto\x1a+marketplace/mallpoints/v1/user_points.proto\"\x14\n" +
	"\x12QueryParamsRequest\"[\n" +
	"\x13QueryParamsResponse\x12D\n" +
	"\x06params\x18\x01 \x01(\v2!.marketplace.mallpoints.v1.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params\"1\n" +
	"\x19QueryGetUserPointsRequest\x12\x14\n" +
	"\x05index\x18\x01 \x01(\tR\x05index\"j\n" +
	"\x1aQueryGetUserPointsResponse\x12L\n" +
	"\vuser_points\x18\x01 \x01(\v2%.marketplace.mallpoints.v1.UserPointsB\x04\xc8\xde\x1f\x00R\n" +
	"userPoints\"c\n" +
	"\x19QueryAllUserPointsRequest\x12F\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\"\xb3\x01\n" +
	"\x1aQueryAllUserPointsResponse\x12L\n" +
	"\vuser_points\x18\x01 \x03(\v2%.marketplace.mallpoints.v1.UserPointsB\x04\xc8\xde\x1f\x00R\n" +
	"userPoints\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination\"!\n" +
	"\x1fQueryGetConversionWindowRequest\"\x82\x01\n" +
	" QueryGetConversionWindowResponse\x12^\n" +
	"\x11conversion_window\x18\x01 \x01(\v2+.marketplace.mallpoints.v1.ConversionWindowB\x04\xc8\xde\x1f\x00R\x10conversionWindow2\xca\x05\n" +
	"\x05Query\x12\x92\x01\n" +
	"\x06Params\x12-.marketplace.mallpoints.v1.QueryParamsRequest\x1a..marketplace.mallpoints.v1.QueryParamsResponse\")\x82\xd3\xe4\x93\x02#\x12!/marketplace/mallpoints/v1/params\x12\xb4\x01\n" +
	"\rGetUserPoints\x124.marketplace.mallpoints.v1.QueryGetUserPointsRequest\x1a5.marketplace.mallpoints.v1.QueryGetUserPointsResponse\"6\x82\xd3\xe4\x93\x020\x12./marketplace/mallpoints/v1/user_points/{index}\x12\xad\x01\n" +
	"\x0eListUserPoints\x124.marketplace.mallpoints.v1.QueryAllUserPointsRequest\x1a5.marketplace.mallpoints.v1.QueryAllUserPointsResponse\".\x82\xd3\xe4\x93\x02(\x12&/marketplace/mallpoints/v1/user_points\x12\xc4\x01\n" +
	"\x13GetConversionWindow\x12:.marketplace.mallpoints.v1.QueryGetConversionWindowRequest\x1a;.marketplace.mallpoints.v1.QueryGetConversionWindowResponse\"4\x82\xd3\xe4\x93\x02.\x12,/marketplace/mallpoints/v1/conversion_windowB/Z-github.com/tmp/marketplace/x/mallpoints/typesb\x06proto3"

var (
	file_marketplace_mallpoints_v1_query_proto_rawDescOnce sync.Once
	file_marketplace_mallpoints_v1_query_proto_rawDescData []byte
)

func file_marketplace_mallpoints_v1_query_proto_rawDescGZIP() []byte {
	file_marketplace_mallpoints_v1_query_proto_rawDescOnce.Do(func() {
		file_marketplace_mallpoints_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketplace_mallpoints_v1_query_proto_rawDesc), len(file_marketplace_mallpoints_v1_query_proto_rawDesc)))
	})
	return file_marketplace_mallpoints_v1_query_proto_rawDescData
}

var file_marketplace_mallpoints_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_marketplace_mallpoints_v1_query_proto_goTypes = []any{
	(*QueryParamsRequest)(nil),               // 0: marketplace.mallpoints.v1.QueryParamsRequest
	(*QueryParamsResponse)(nil),              // 1: marketplace.mallpoints.v1.QueryParamsResponse
	(*QueryGetUserPointsRequest)(nil),        // 2: marketplace.mallpoints.v1.QueryGetUserPointsRequest
	(*QueryGetUserPointsResponse)(nil),       // 3: marketplace.mallpoints.v1.QueryGetUserPointsResponse
	(*QueryAllUserPointsRequest)(nil),        // 4: marketplace.mallpoints.v1.QueryAllUserPointsRequest
	(*QueryAllUserPointsResponse)(nil),       // 5: marketplace.mallpoints.v1.QueryAllUserPointsResponse
	(*QueryGetConversionWindowRequest)(nil),  // 6: marketplace.mallpoints.v1.QueryGetConversionWindowRequest
	(*QueryGetConversionWindowResponse)(nil), // 7: marketplace.mallpoints.v1.QueryGetConversionWindowResponse
	(*Params)(nil),                           // 8: marketplace.mallpoints.v1.Params
	(*UserPoints)(nil),                       // 9: marketplace.mallpoints.v1.UserPoints
	(*query.PageRequest)(nil),                // 10: cosmos.base.query.v1beta1.PageRequest
	(*query.PageResponse)(nil),               // 11: cosmos.base.query.v1beta1.PageResponse
	(*ConversionWindow)(nil),                 // 12: marketplace.mallpoints.v1.ConversionWindow
}
var file_marketplace_mallpoints_v1_query_proto_depIdxs = []int32{
	8,  // 0: marketplace.mallpoints.v1.QueryParamsResponse.params:type_name -> marketplace.mallpoints.v1.Params
	9,  // 1: marketplace.mallpoints.v1.QueryGetUserPointsResponse.user_points:type_name -> marketplace.mallpoints.v1.UserPoints
	10, // 2: marketplace.mallpoints.v1.QueryAllUserPointsRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	9,  // 3: marketplace.mallpoints.v1.QueryAllUserPointsResponse.user_points:type_name -> marketplace.mallpoints.v1.UserPoints
	11, // 4: marketplace.mallpoints.v1.QueryAllUserPointsResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	12, // 5: marketplace.mallpoints.v1.QueryGetConversionWindowResponse.conversion_window:type_name -> marketplace.mallpoints.v1.ConversionWindow
	0,  // 6: marketplace.mallpoints.v1.Query.Params:input_type -> marketplace.mallpoints.v1.QueryParamsRequest
	2,  // 7: marketplace.mallpoints.v1.Query.GetUserPoints:input_type -> marketplace.mallpoints.v1.QueryGetUserPointsRequest
	4,  // 8: marketplace.mallpoints.v1.Query.ListUserPoints:input_type -> marketplace.mallpoints.v1.QueryAllUserPointsRequest
	6,  // 9: marketplace.mallpoints.v1.Query.GetConversionWindow:input_type -> marketplace.mallpoints.v1.QueryGetConversionWindowRequest
	1,  // 10: marketplace.mallpoints.v1.Query.Params:output_type -> marketplace.mallpoints.v1.QueryParamsResponse
	3,  // 11: marketplace.mallpoints.v1.Query.GetUserPoints:output_type -> marketplace.mallpoints.v1.QueryGetUserPointsResponse
	5,  // 12: marketplace.mallpoints.v1.Query.ListUserPoints:output_type -> marketplace.mallpoints.v1.QueryAllUserPointsResponse
	7,  // 13: marketplace.mallpoints.v1.Query.GetConversionWindow:output_type -> marketplace.mallpoints.v1.QueryGetConversionWindowResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_marketplace_mallpoints_v1_query_proto_init() }
func file_marketplace_mallpoints_v1_query_proto_init() {
	if File_marketplace_mallpoints_v1_query_proto != nil {
		return
	}
	file_marketplace_mallpoints_v1_conversion_window_proto_init()
	file_marketplace_mallpoints_v1_params_proto_init()
	file_marketplace_mallpoints_v1_user_points_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketplace_mallpoints_v1_query_proto_rawDesc), len(file_marketplace_mallpoints_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marketplace_mallpoints_v1_query_proto_goTypes,
		DependencyIndexes: file_marketplace_mallpoints_v1_query_proto_depIdxs,
		MessageInfos:      file_marketplace_mallpoints_v1_query_proto_msgTypes,
	}.Build()
	File_marketplace_mallpoints_v1_query_proto = out.File
	file_marketplace_mallpoints_v1_query_proto_goTypes = nil
	file_marketplace_mallpoints_v1_query_proto_depIdxs = nil
}
