// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: marketplace/mallpoints/v1/user_points.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserPoints defines the UserPoints message.
type UserPoints struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Index          string                 `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Address        string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Points         uint64                 `protobuf:"varint,3,opt,name=points,proto3" json:"points,omitempty"`
	TasksCompleted uint64                 `protobuf:"varint,4,opt,name=tasks_completed,json=tasksCompleted,proto3" json:"tasks_completed,omitempty"`
	LastEarned     uint64                 `protobuf:"varint,5,opt,name=last_earned,json=lastEarned,proto3" json:"last_earned,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserPoints) Reset() {
	*x = UserPoints{}
	mi := &file_marketplace_mallpoints_v1_user_points_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPoints) ProtoMessage() {}

func (x *UserPoints) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mallpoints_v1_user_points_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPoints.ProtoReflect.Descriptor instead.
func (*UserPoints) Descriptor() ([]byte, []int) {
	return file_marketplace_mallpoints_v1_user_points_proto_rawDescGZIP(), []int{0}
}

func (x *UserPoints) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *UserPoints) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UserPoints) GetPoints() uint64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *UserPoints) GetTasksCompleted() uint64 {
	if x != nil {
		return x.TasksCompleted
	}
	return 0
}

func (x *UserPoints) GetLastEarned() uint64 {
	if x != nil {
		return x.LastEarned
	}
	return 0
}

var File_marketplace_mallpoints_v1_user_points_proto protoreflect.FileDescriptor

const file_marketplace_mallpoints_v1_user_points_proto_rawDesc = "" +
	"\n" +
	"+marketplace/mallpoints/v1/user_points.proto\x12\x19marketplace.mallpoints.v1\"\x9e\x01\n" +
	"\n" +
	"UserPoints\x12\x14\n" +
	"\x05index\x18\x01 \x01(\tR\x05index\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06points\x18\x03 \x01(\x04R\x06points\x12'\n" +
	"\x0ftasks_completed\x18\x04 \x01(\x04R\x0etasksCompleted\x12\x1f\n" +
	"\vlast_earned\x18\x05 \x01(\x04R\n" +
	"lastEarnedB/Z-github.com/tmp/marketplace/x/mallpoints/typesb\x06proto3"

var (
	file_marketplace_mallpoints_v1_user_points_proto_rawDescOnce sync.Once
	file_marketplace_mallpoints_v1_user_points_proto_rawDescData []byte
)

func file_marketplace_mallpoints_v1_user_points_proto_rawDescGZIP() []byte {
	file_marketplace_mallpoints_v1_user_points_proto_rawDescOnce.Do(func() {
		file_marketplace_mallpoints_v1_user_points_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketplace_mallpoints_v1_user_points_proto_rawDesc), len(file_marketplace_mallpoints_v1_user_points_proto_rawDesc)))
	})
	return file_marketplace_mallpoints_v1_user_points_proto_rawDescData
}

var file_marketplace_mallpoints_v1_user_points_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_marketplace_mallpoints_v1_user_points_proto_goTypes = []any{
	(*UserPoints)(nil), // 0: marketplace.mallpoints.v1.UserPoints
}
var file_marketplace_mallpoints_v1_user_points_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_marketplace_mallpoints_v1_user_points_proto_init() }
func file_marketplace_mallpoints_v1_user_points_proto_init() {
	if File_marketplace_mallpoints_v1_user_points_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketplace_mallpoints_v1_user_points_proto_rawDesc), len(file_marketplace_mallpoints_v1_user_points_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_marketplace_mallpoints_v1_user_points_proto_goTypes,
		DependencyIndexes: file_marketplace_mallpoints_v1_user_points_proto_depIdxs,
		MessageInfos:      file_marketplace_mallpoints_v1_user_points_proto_msgTypes,
	}.Build()
	File_marketplace_mallpoints_v1_user_points_proto = out.File
	file_marketplace_mallpoints_v1_user_points_proto_goTypes = nil
	file_marketplace_mallpoints_v1_user_points_proto_depIdxs = nil
}
