// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: marketplace/vault/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgSetupVault registers the KDF parameters and an already-encrypted TOTP
// secret for `authority`'s vault. The client generates the TOTP secret and
// its own salt locally, derives the Argon2id key from the user's password
// in-browser, encrypts the secret with it, and submits only the resulting
// ciphertext here.
type MsgSetupVault struct {
	Authority           string `protobuf:"bytes,1,opt,name=authority,proto3,casttype=string" json:"authority,omitempty" yaml:"authority"`
	Salt                string `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	KdfTime             uint32 `protobuf:"varint,3,opt,name=kdf_time,json=kdfTime,proto3" json:"kdf_time,omitempty"`
	KdfMemory           uint32 `protobuf:"varint,4,opt,name=kdf_memory,json=kdfMemory,proto3" json:"kdf_memory,omitempty"`
	KdfThreads          uint32 `protobuf:"varint,5,opt,name=kdf_threads,json=kdfThreads,proto3" json:"kdf_threads,omitempty"`
	KdfKeyLen           uint32 `protobuf:"varint,6,opt,name=kdf_key_len,json=kdfKeyLen,proto3" json:"kdf_key_len,omitempty"`
	NonceTotp           string `protobuf:"bytes,7,opt,name=nonce_totp,json=nonceTotp,proto3" json:"nonce_totp,omitempty"`
	EncryptedTotpSecret string `protobuf:"bytes,8,opt,name=encrypted_totp_secret,json=encryptedTotpSecret,proto3" json:"encrypted_totp_secret,omitempty"`
}

func (m *MsgSetupVault) Reset()         { *m = MsgSetupVault{} }
func (m *MsgSetupVault) String() string { return proto.CompactTextString(m) }
func (*MsgSetupVault) ProtoMessage()    {}
func (*MsgSetupVault) Descriptor() ([]byte, []int) {
	return fileDescriptor_62733f43e31364a6, []int{0}
}
func (m *MsgSetupVault) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetupVault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetupVault.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetupVault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetupVault.Merge(m, src)
}
func (m *MsgSetupVault) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetupVault) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetupVault.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetupVault proto.InternalMessageInfo

func (m *MsgSetupVault) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgSetupVault) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

func (m *MsgSetupVault) GetKdfTime() uint32 {
	if m != nil {
		return m.KdfTime
	}
	return 0
}

func (m *MsgSetupVault) GetKdfMemory() uint32 {
	if m != nil {
		return m.KdfMemory
	}
	return 0
}

func (m *MsgSetupVault) GetKdfThreads() uint32 {
	if m != nil {
		return m.KdfThreads
	}
	return 0
}

func (m *MsgSetupVault) GetKdfKeyLen() uint32 {
	if m != nil {
		return m.KdfKeyLen
	}
	return 0
}

func (m *MsgSetupVault) GetNonceTotp() string {
	if m != nil {
		return m.NonceTotp
	}
	return ""
}

func (m *MsgSetupVault) GetEncryptedTotpSecret() string {
	if m != nil {
		return m.EncryptedTotpSecret
	}
	return ""
}

type MsgSetupVaultResponse struct {
}

func (m *MsgSetupVaultResponse) Reset()         { *m = MsgSetupVaultResponse{} }
func (m *MsgSetupVaultResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetupVaultResponse) ProtoMessage()    {}
func (*MsgSetupVaultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62733f43e31364a6, []int{1}
}
func (m *MsgSetupVaultResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetupVaultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetupVaultResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetupVaultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetupVaultResponse.Merge(m, src)
}
func (m *MsgSetupVaultResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetupVaultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetupVaultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetupVaultResponse proto.InternalMessageInfo

// MsgConfirmVault finalizes a vault by storing the client-encrypted ed25519
// signing key, once the client has verified locally (by decrypting its own
// just-submitted TOTP secret and checking a live code) that the user saved
// their authenticator entry correctly.
type MsgConfirmVault struct {
	Authority  string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	NoncePriv  string `protobuf:"bytes,2,opt,name=nonce_priv,json=noncePriv,proto3" json:"nonce_priv,omitempty"`
	Ciphertext string `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	PublicKey  string `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (m *MsgConfirmVault) Reset()         { *m = MsgConfirmVault{} }
func (m *MsgConfirmVault) String() string { return proto.CompactTextString(m) }
func (*MsgConfirmVault) ProtoMessage()    {}
func (*MsgConfirmVault) Descriptor() ([]byte, []int) {
	return fileDescriptor_62733f43e31364a6, []int{2}
}
func (m *MsgConfirmVault) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConfirmVault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConfirmVault.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConfirmVault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConfirmVault.Merge(m, src)
}
func (m *MsgConfirmVault) XXX_Size() int {
	return m.Size()
}
func (m *MsgConfirmVault) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConfirmVault.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConfirmVault proto.InternalMessageInfo

func (m *MsgConfirmVault) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgConfirmVault) GetNoncePriv() string {
	if m != nil {
		return m.NoncePriv
	}
	return ""
}

func (m *MsgConfirmVault) GetCiphertext() string {
	if m != nil {
		return m.Ciphertext
	}
	return ""
}

func (m *MsgConfirmVault) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type MsgConfirmVaultResponse struct {
}

func (m *MsgConfirmVaultResponse) Reset()         { *m = MsgConfirmVaultResponse{} }
func (m *MsgConfirmVaultResponse) String() string { return proto.CompactTextString(m) }
func (*MsgConfirmVaultResponse) ProtoMessage()    {}
func (*MsgConfirmVaultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62733f43e31364a6, []int{3}
}
func (m *MsgConfirmVaultResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConfirmVaultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConfirmVaultResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConfirmVaultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConfirmVaultResponse.Merge(m, src)
}
func (m *MsgConfirmVaultResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgConfirmVaultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConfirmVaultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConfirmVaultResponse proto.InternalMessageInfo

// MsgDisableVault deletes `authority`'s vault record. Authorization is the
// normal Cosmos Msg signer check (only the account itself can sign this) —
// no separate password/TOTP factor is meaningful here since, as above, the
// chain can't verify either without seeing them in the clear.
type MsgDisableVault struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
}

func (m *MsgDisableVault) Reset()         { *m = MsgDisableVault{} }
func (m *MsgDisableVault) String() string { return proto.CompactTextString(m) }
func (*MsgDisableVault) ProtoMessage()    {}
func (*MsgDisableVault) Descriptor() ([]byte, []int) {
	return fileDescriptor_62733f43e31364a6, []int{4}
}
func (m *MsgDisableVault) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDisableVault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDisableVault.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDisableVault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDisableVault.Merge(m, src)
}
func (m *MsgDisableVault) XXX_Size() int {
	return m.Size()
}
func (m *MsgDisableVault) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDisableVault.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDisableVault proto.InternalMessageInfo

func (m *MsgDisableVault) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

type MsgDisableVaultResponse struct {
}

func (m *MsgDisableVaultResponse) Reset()         { *m = MsgDisableVaultResponse{} }
func (m *MsgDisableVaultResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDisableVaultResponse) ProtoMessage()    {}
func (*MsgDisableVaultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62733f43e31364a6, []int{5}
}
func (m *MsgDisableVaultResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDisableVaultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDisableVaultResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDisableVaultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDisableVaultResponse.Merge(m, src)
}
func (m *MsgDisableVaultResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDisableVaultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDisableVaultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDisableVaultResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSetupVault)(nil), "marketplace.vault.v1.MsgSetupVault")
	proto.RegisterType((*MsgSetupVaultResponse)(nil), "marketplace.vault.v1.MsgSetupVaultResponse")
	proto.RegisterType((*MsgConfirmVault)(nil), "marketplace.vault.v1.MsgConfirmVault")
	proto.RegisterType((*MsgConfirmVaultResponse)(nil), "marketplace.vault.v1.MsgConfirmVaultResponse")
	proto.RegisterType((*MsgDisableVault)(nil), "marketplace.vault.v1.MsgDisableVault")
	proto.RegisterType((*MsgDisableVaultResponse)(nil), "marketplace.vault.v1.MsgDisableVaultResponse")
}

func init() { proto.RegisterFile("marketplace/vault/v1/tx.proto", fileDescriptor_62733f43e31364a6) }

var fileDescriptor_62733f43e31364a6 = []byte{
	// 550 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x3d, 0x6f, 0xd3, 0x40,
	0x18, 0x8e, 0xd3, 0x36, 0xad, 0x0f, 0x2a, 0xd0, 0xd1, 0x2a, 0x4e, 0x44, 0x9d, 0xca, 0x08, 0x29,
	0x02, 0x61, 0xab, 0x65, 0x43, 0x4c, 0x81, 0xad, 0x44, 0x42, 0x6e, 0xc4, 0xc0, 0x12, 0x1c, 0xe7,
	0x8d, 0x73, 0x8a, 0xcf, 0x77, 0xba, 0xbb, 0x44, 0xf1, 0xc6, 0x1f, 0x40, 0xe2, 0x9f, 0xc0, 0x2f,
	0x60, 0x66, 0xec, 0xc8, 0x54, 0xa1, 0x64, 0x60, 0x67, 0x64, 0x42, 0x3e, 0x07, 0xe3, 0x40, 0x5b,
	0x65, 0xbb, 0xbc, 0xcf, 0xc7, 0xfb, 0xe4, 0xd1, 0xf9, 0xd0, 0x11, 0x0d, 0xc4, 0x04, 0x14, 0x8f,
	0x83, 0x10, 0xbc, 0x59, 0x30, 0x8d, 0x95, 0x37, 0x3b, 0xf1, 0xd4, 0xdc, 0xe5, 0x82, 0x29, 0x86,
	0x0f, 0x4a, 0xb0, 0xab, 0x61, 0x77, 0x76, 0xd2, 0x3c, 0x88, 0x58, 0xc4, 0x34, 0xc1, 0xcb, 0x4e,
	0x39, 0xb7, 0x59, 0x0f, 0x99, 0xa4, 0x4c, 0x7a, 0x54, 0x46, 0x99, 0x07, 0x95, 0xd1, 0x0a, 0x68,
	0xe4, 0x40, 0x3f, 0x57, 0xe4, 0x3f, 0x72, 0xc8, 0xf9, 0x54, 0x45, 0xfb, 0x5d, 0x19, 0x9d, 0x83,
	0x9a, 0xf2, 0x37, 0x99, 0x3d, 0x7e, 0x8e, 0xcc, 0x60, 0xaa, 0xc6, 0x4c, 0x10, 0x95, 0x5a, 0xc6,
	0xb1, 0xd1, 0x36, 0x3b, 0xf6, 0xcf, 0xcb, 0xd6, 0xdd, 0x34, 0xa0, 0xf1, 0x33, 0xa7, 0x80, 0x9c,
	0x5f, 0x97, 0xad, 0x9a, 0x54, 0x82, 0x24, 0x91, 0xff, 0x57, 0x80, 0x31, 0xda, 0x96, 0x41, 0xac,
	0xac, 0x6a, 0x26, 0xf4, 0xf5, 0x19, 0x37, 0xd0, 0xde, 0x64, 0x38, 0xea, 0x2b, 0x42, 0xc1, 0xda,
	0x3a, 0x36, 0xda, 0xfb, 0xfe, 0xee, 0x64, 0x38, 0xea, 0x11, 0x0a, 0xf8, 0x08, 0xa1, 0x0c, 0xa2,
	0x40, 0x99, 0x48, 0xad, 0x6d, 0x0d, 0x9a, 0x93, 0xe1, 0xa8, 0xab, 0x07, 0xb8, 0x85, 0x6e, 0x69,
	0xe5, 0x58, 0x40, 0x30, 0x94, 0xd6, 0x8e, 0xc6, 0x33, 0x45, 0x2f, 0x9f, 0x60, 0x3b, 0x27, 0x4c,
	0x20, 0xed, 0xc7, 0x90, 0x58, 0xb5, 0xc2, 0xe0, 0x0c, 0xd2, 0x57, 0x90, 0x64, 0xfe, 0x09, 0x4b,
	0x42, 0xe8, 0x2b, 0xa6, 0xb8, 0xb5, 0xab, 0x43, 0x99, 0x7a, 0xd2, 0x63, 0x8a, 0xe3, 0x53, 0x74,
	0x08, 0x49, 0x28, 0x52, 0xae, 0x60, 0xa8, 0x29, 0x7d, 0x09, 0xa1, 0x00, 0x65, 0xed, 0x69, 0xe6,
	0xbd, 0x02, 0xcc, 0xd8, 0xe7, 0x1a, 0x72, 0xea, 0xe8, 0x70, 0xad, 0x30, 0x1f, 0x24, 0x67, 0x89,
	0x04, 0xe7, 0x83, 0x81, 0xee, 0x74, 0x65, 0xf4, 0x82, 0x25, 0x23, 0x22, 0x68, 0x5e, 0xe6, 0xfd,
	0xff, 0xca, 0x2c, 0x97, 0x55, 0xa4, 0xe3, 0x82, 0xcc, 0x56, 0x95, 0xe5, 0xe9, 0x5e, 0x0b, 0x32,
	0xc3, 0x36, 0x42, 0x21, 0xe1, 0x63, 0x10, 0x0a, 0xe6, 0x4a, 0x37, 0x67, 0xfa, 0xa5, 0x49, 0x26,
	0xe7, 0xd3, 0x41, 0x4c, 0xc2, 0xec, 0xff, 0xeb, 0xf2, 0x4c, 0xdf, 0xcc, 0x27, 0x67, 0x90, 0x3a,
	0x0d, 0x54, 0xff, 0x27, 0x4e, 0x11, 0xd5, 0xd3, 0x49, 0x5f, 0x12, 0x19, 0x0c, 0x62, 0xd8, 0x20,
	0xe9, 0xca, 0xab, 0x2c, 0xf8, 0xe3, 0x75, 0xfa, 0xa5, 0x8a, 0xb6, 0xba, 0x32, 0xc2, 0xef, 0x10,
	0x2a, 0xdd, 0xa2, 0x07, 0xee, 0x55, 0x17, 0xd7, 0x5d, 0x6b, 0xae, 0xf9, 0x78, 0x03, 0x52, 0x91,
	0xb9, 0x82, 0x47, 0xe8, 0xf6, 0x5a, 0xb9, 0x0f, 0xaf, 0x95, 0x97, 0x69, 0xcd, 0x27, 0x1b, 0xd1,
	0xd6, 0xf7, 0xac, 0x55, 0x73, 0xfd, 0x9e, 0x32, 0xed, 0x86, 0x3d, 0x57, 0xf5, 0xe6, 0x54, 0x9a,
	0x3b, 0xef, 0x7f, 0x7c, 0x7e, 0x64, 0x74, 0x3a, 0x5f, 0x17, 0xb6, 0x71, 0xb1, 0xb0, 0x8d, 0xef,
	0x0b, 0xdb, 0xf8, 0xb8, 0xb4, 0x2b, 0x17, 0x4b, 0xbb, 0xf2, 0x6d, 0x69, 0x57, 0xde, 0xb6, 0x23,
	0xa2, 0xc6, 0xd3, 0x81, 0x1b, 0x32, 0xea, 0x29, 0xca, 0xbd, 0xf2, 0x53, 0x31, 0x5f, 0x3d, 0x16,
	0x2a, 0xe5, 0x20, 0x07, 0x35, 0xfd, 0x35, 0x3f, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x21, 0xc4,
	0x2c, 0x63, 0x4e, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SetupVault(ctx context.Context, in *MsgSetupVault, opts ...grpc.CallOption) (*MsgSetupVaultResponse, error)
	ConfirmVault(ctx context.Context, in *MsgConfirmVault, opts ...grpc.CallOption) (*MsgConfirmVaultResponse, error)
	DisableVault(ctx context.Context, in *MsgDisableVault, opts ...grpc.CallOption) (*MsgDisableVaultResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SetupVault(ctx context.Context, in *MsgSetupVault, opts ...grpc.CallOption) (*MsgSetupVaultResponse, error) {
	out := new(MsgSetupVaultResponse)
	err := c.cc.Invoke(ctx, "/marketplace.vault.v1.Msg/SetupVault", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ConfirmVault(ctx context.Context, in *MsgConfirmVault, opts ...grpc.CallOption) (*MsgConfirmVaultResponse, error) {
	out := new(MsgConfirmVaultResponse)
	err := c.cc.Invoke(ctx, "/marketplace.vault.v1.Msg/ConfirmVault", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DisableVault(ctx context.Context, in *MsgDisableVault, opts ...grpc.CallOption) (*MsgDisableVaultResponse, error) {
	out := new(MsgDisableVaultResponse)
	err := c.cc.Invoke(ctx, "/marketplace.vault.v1.Msg/DisableVault", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SetupVault(context.Context, *MsgSetupVault) (*MsgSetupVaultResponse, error)
	ConfirmVault(context.Context, *MsgConfirmVault) (*MsgConfirmVaultResponse, error)
	DisableVault(context.Context, *MsgDisableVault) (*MsgDisableVaultResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SetupVault(ctx context.Context, req *MsgSetupVault) (*MsgSetupVaultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupVault not implemented")
}
func (*UnimplementedMsgServer) ConfirmVault(ctx context.Context, req *MsgConfirmVault) (*MsgConfirmVaultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmVault not implemented")
}
func (*UnimplementedMsgServer) DisableVault(ctx context.Context, req *MsgDisableVault) (*MsgDisableVaultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableVault not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SetupVault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetupVault)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetupVault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/marketplace.vault.v1.Msg/SetupVault",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetupVault(ctx, req.(*MsgSetupVault))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ConfirmVault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgConfirmVault)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ConfirmVault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/marketplace.vault.v1.Msg/ConfirmVault",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ConfirmVault(ctx, req.(*MsgConfirmVault))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DisableVault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDisableVault)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DisableVault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/marketplace.vault.v1.Msg/DisableVault",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DisableVault(ctx, req.(*MsgDisableVault))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "marketplace.vault.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetupVault",
			Handler:    _Msg_SetupVault_Handler,
		},
		{
			MethodName: "ConfirmVault",
			Handler:    _Msg_ConfirmVault_Handler,
		},
		{
			MethodName: "DisableVault",
			Handler:    _Msg_DisableVault_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "marketplace/vault/v1/tx.proto",
}

func (m *MsgSetupVault) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetupVault) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetupVault) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EncryptedTotpSecret) > 0 {
		i -= len(m.EncryptedTotpSecret)
		copy(dAtA[i:], m.EncryptedTotpSecret)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EncryptedTotpSecret)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.NonceTotp) > 0 {
		i -= len(m.NonceTotp)
		copy(dAtA[i:], m.NonceTotp)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NonceTotp)))
		i--
		dAtA[i] = 0x3a
	}
	if m.KdfKeyLen != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.KdfKeyLen))
		i--
		dAtA[i] = 0x30
	}
	if m.KdfThreads != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.KdfThreads))
		i--
		dAtA[i] = 0x28
	}
	if m.KdfMemory != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.KdfMemory))
		i--
		dAtA[i] = 0x20
	}
	if m.KdfTime != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.KdfTime))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Salt) > 0 {
		i -= len(m.Salt)
		copy(dAtA[i:], m.Salt)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Salt)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetupVaultResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetupVaultResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetupVaultResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgConfirmVault) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConfirmVault) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConfirmVault) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Ciphertext) > 0 {
		i -= len(m.Ciphertext)
		copy(dAtA[i:], m.Ciphertext)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Ciphertext)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.NoncePriv) > 0 {
		i -= len(m.NoncePriv)
		copy(dAtA[i:], m.NoncePriv)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NoncePriv)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgConfirmVaultResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConfirmVaultResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConfirmVaultResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDisableVault) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDisableVault) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDisableVault) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDisableVaultResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDisableVaultResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDisableVaultResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSetupVault) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Salt)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.KdfTime != 0 {
		n += 1 + sovTx(uint64(m.KdfTime))
	}
	if m.KdfMemory != 0 {
		n += 1 + sovTx(uint64(m.KdfMemory))
	}
	if m.KdfThreads != 0 {
		n += 1 + sovTx(uint64(m.KdfThreads))
	}
	if m.KdfKeyLen != 0 {
		n += 1 + sovTx(uint64(m.KdfKeyLen))
	}
	l = len(m.NonceTotp)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EncryptedTotpSecret)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSetupVaultResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgConfirmVault) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NoncePriv)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Ciphertext)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgConfirmVaultResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDisableVault) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDisableVaultResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSetupVault) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetupVault: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetupVault: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Salt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Salt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KdfTime", wireType)
			}
			m.KdfTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KdfTime |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KdfMemory", wireType)
			}
			m.KdfMemory = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KdfMemory |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KdfThreads", wireType)
			}
			m.KdfThreads = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KdfThreads |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KdfKeyLen", wireType)
			}
			m.KdfKeyLen = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KdfKeyLen |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NonceTotp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NonceTotp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptedTotpSecret", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EncryptedTotpSecret = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetupVaultResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetupVaultResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetupVaultResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgConfirmVault) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConfirmVault: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConfirmVault: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NoncePriv", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NoncePriv = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ciphertext", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ciphertext = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgConfirmVaultResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConfirmVaultResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConfirmVaultResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDisableVault) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDisableVault: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDisableVault: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDisableVaultResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDisableVaultResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDisableVaultResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
