// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: marketplace/badge/v1/query.proto

package types

import (
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_marketplace_badge_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_badge_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_marketplace_badge_v1_query_proto_rawDescGZIP(), []int{0}
}

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// params holds all the parameters of this module.
	Params        *Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_marketplace_badge_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_badge_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_badge_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

// QueryGetUserBadgeRequest defines the QueryGetUserBadgeRequest message.
type QueryGetUserBadgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         string                 `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGetUserBadgeRequest) Reset() {
	*x = QueryGetUserBadgeRequest{}
	mi := &file_marketplace_badge_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGetUserBadgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGetUserBadgeRequest) ProtoMessage() {}

func (x *QueryGetUserBadgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_badge_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGetUserBadgeRequest.ProtoReflect.Descriptor instead.
func (*QueryGetUserBadgeRequest) Descriptor() ([]byte, []int) {
	return file_marketplace_badge_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryGetUserBadgeRequest) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

// QueryGetUserBadgeResponse defines the QueryGetUserBadgeResponse message.
type QueryGetUserBadgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserBadge     *UserBadge             `protobuf:"bytes,1,opt,name=user_badge,json=userBadge,proto3" json:"user_badge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryGetUserBadgeResponse) Reset() {
	*x = QueryGetUserBadgeResponse{}
	mi := &file_marketplace_badge_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGetUserBadgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGetUserBadgeResponse) ProtoMessage() {}

func (x *QueryGetUserBadgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_badge_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGetUserBadgeResponse.ProtoReflect.Descriptor instead.
func (*QueryGetUserBadgeResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_badge_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryGetUserBadgeResponse) GetUserBadge() *UserBadge {
	if x != nil {
		return x.UserBadge
	}
	return nil
}

// QueryAllUserBadgeRequest defines the QueryAllUserBadgeRequest message.
type QueryAllUserBadgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *query.PageRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAllUserBadgeRequest) Reset() {
	*x = QueryAllUserBadgeRequest{}
	mi := &file_marketplace_badge_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAllUserBadgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAllUserBadgeRequest) ProtoMessage() {}

func (x *QueryAllUserBadgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_badge_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAllUserBadgeRequest.ProtoReflect.Descriptor instead.
func (*QueryAllUserBadgeRequest) Descriptor() ([]byte, []int) {
	return file_marketplace_badge_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryAllUserBadgeRequest) GetPagination() *query.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// QueryAllUserBadgeResponse defines the QueryAllUserBadgeResponse message.
type QueryAllUserBadgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserBadge     []*UserBadge           `protobuf:"bytes,1,rep,name=user_badge,json=userBadge,proto3" json:"user_badge,omitempty"`
	Pagination    *query.PageResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAllUserBadgeResponse) Reset() {
	*x = QueryAllUserBadgeResponse{}
	mi := &file_marketplace_badge_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAllUserBadgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAllUserBadgeResponse) ProtoMessage() {}

func (x *QueryAllUserBadgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_badge_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAllUserBadgeResponse.ProtoReflect.Descriptor instead.
func (*QueryAllUserBadgeResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_badge_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryAllUserBadgeResponse) GetUserBadge() []*UserBadge {
	if x != nil {
		return x.UserBadge
	}
	return nil
}

func (x *QueryAllUserBadgeResponse) GetPagination() *query.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_marketplace_badge_v1_query_proto protoreflect.FileDescriptor

const file_marketplace_badge_v1_query_proto_rawDesc = "" +
	"\n" +
	" marketplace/badge/v1/query.proto\x12\x14marketplace.badge.v1\x1a\x11amino/amino.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\x1a!marketplace/badge/v1/params.proto\x1a%marketplace/badge/v1/user_badge.proto\"\x14\n" +
	"\x12QueryParamsRequest\"V\n" +
	"\x13QueryParamsResponse\x12?\n" +
	"\x06params\x18\x01 \x01(\v2\x1c.marketplace.badge.v1.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params\"0\n" +
	"\x18QueryGetUserBadgeRequest\x12\x14\n" +
	"\x05index\x18\x01 \x01(\tR\x05index\"a\n" +
	"\x19QueryGetUserBadgeResponse\x12D\n" +
	"\n" +
	"user_badge\x18\x01 \x01(\v2\x1f.marketplace.badge.v1.UserBadgeB\x04\xc8\xde\x1f\x00R\tuserBadge\"b\n" +
	"\x18QueryAllUserBadgeRequest\x12F\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\"\xaa\x01\n" +
	"\x19QueryAllUserBadgeResponse\x12D\n" +
	"\n" +
	"user_badge\x18\x01 \x03(\v2\x1f.marketplace.badge.v1.UserBadgeB\x04\xc8\xde\x1f\x00R\tuserBadge\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination2\xda\x03\n" +
	"\x05Query\x12\x87\x01\n" +
	"\x06Params\x12(.marketplace.badge.v1.QueryParamsRequest\x1a).marketplace.badge.v1.QueryParamsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /tmp/marketplace/badge/v1/params\x12\xa5\x01\n" +
	"\fGetUserBadge\x12..marketplace.badge.v1.QueryGetUserBadgeRequest\x1a/.marketplace.badge.v1.QueryGetUserBadgeResponse\"4\x82\xd3\xe4\x93\x02.\x12,/tmp/marketplace/badge/v1/user_badge/{index}\x12\x9e\x01\n" +
	"\rListUserBadge\x12..marketplace.badge.v1.QueryAllUserBadgeRequest\x1a/.marketplace.badge.v1.QueryAllUserBadgeResponse\",\x82\xd3\xe4\x93\x02&\x12$/tmp/marketplace/badge/v1/user_badgeB*Z(github.com/tmp/marketplace/x/badge/typesb\x06proto3"

var (
	file_marketplace_badge_v1_query_proto_rawDescOnce sync.Once
	file_marketplace_badge_v1_query_proto_rawDescData []byte
)

func file_marketplace_badge_v1_query_proto_rawDescGZIP() []byte {
	file_marketplace_badge_v1_query_proto_rawDescOnce.Do(func() {
		file_marketplace_badge_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketplace_badge_v1_query_proto_rawDesc), len(file_marketplace_badge_v1_query_proto_rawDesc)))
	})
	return file_marketplace_badge_v1_query_proto_rawDescData
}

var file_marketplace_badge_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_marketplace_badge_v1_query_proto_goTypes = []any{
	(*QueryParamsRequest)(nil),        // 0: marketplace.badge.v1.QueryParamsRequest
	(*QueryParamsResponse)(nil),       // 1: marketplace.badge.v1.QueryParamsResponse
	(*QueryGetUserBadgeRequest)(nil),  // 2: marketplace.badge.v1.QueryGetUserBadgeRequest
	(*QueryGetUserBadgeResponse)(nil), // 3: marketplace.badge.v1.QueryGetUserBadgeResponse
	(*QueryAllUserBadgeRequest)(nil),  // 4: marketplace.badge.v1.QueryAllUserBadgeRequest
	(*QueryAllUserBadgeResponse)(nil), // 5: marketplace.badge.v1.QueryAllUserBadgeResponse
	(*Params)(nil),                    // 6: marketplace.badge.v1.Params
	(*UserBadge)(nil),                 // 7: marketplace.badge.v1.UserBadge
	(*query.PageRequest)(nil),         // 8: cosmos.base.query.v1beta1.PageRequest
	(*query.PageResponse)(nil),        // 9: cosmos.base.query.v1beta1.PageResponse
}
var file_marketplace_badge_v1_query_proto_depIdxs = []int32{
	6, // 0: marketplace.badge.v1.QueryParamsResponse.params:type_name -> marketplace.badge.v1.Params
	7, // 1: marketplace.badge.v1.QueryGetUserBadgeResponse.user_badge:type_name -> marketplace.badge.v1.UserBadge
	8, // 2: marketplace.badge.v1.QueryAllUserBadgeRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	7, // 3: marketplace.badge.v1.QueryAllUserBadgeResponse.user_badge:type_name -> marketplace.badge.v1.UserBadge
	9, // 4: marketplace.badge.v1.QueryAllUserBadgeResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	0, // 5: marketplace.badge.v1.Query.Params:input_type -> marketplace.badge.v1.QueryParamsRequest
	2, // 6: marketplace.badge.v1.Query.GetUserBadge:input_type -> marketplace.badge.v1.QueryGetUserBadgeRequest
	4, // 7: marketplace.badge.v1.Query.ListUserBadge:input_type -> marketplace.badge.v1.QueryAllUserBadgeRequest
	1, // 8: marketplace.badge.v1.Query.Params:output_type -> marketplace.badge.v1.QueryParamsResponse
	3, // 9: marketplace.badge.v1.Query.GetUserBadge:output_type -> marketplace.badge.v1.QueryGetUserBadgeResponse
	5, // 10: marketplace.badge.v1.Query.ListUserBadge:output_type -> marketplace.badge.v1.QueryAllUserBadgeResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_marketplace_badge_v1_query_proto_init() }
func file_marketplace_badge_v1_query_proto_init() {
	if File_marketplace_badge_v1_query_proto != nil {
		return
	}
	file_marketplace_badge_v1_params_proto_init()
	file_marketplace_badge_v1_user_badge_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketplace_badge_v1_query_proto_rawDesc), len(file_marketplace_badge_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marketplace_badge_v1_query_proto_goTypes,
		DependencyIndexes: file_marketplace_badge_v1_query_proto_depIdxs,
		MessageInfos:      file_marketplace_badge_v1_query_proto_msgTypes,
	}.Build()
	File_marketplace_badge_v1_query_proto = out.File
	file_marketplace_badge_v1_query_proto_goTypes = nil
	file_marketplace_badge_v1_query_proto_depIdxs = nil
}
