// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: marketplace/badge/v1/user_badge.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserBadge defines the UserBadge message.
type UserBadge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         string                 `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	HasBadge      bool                   `protobuf:"varint,3,opt,name=has_badge,json=hasBadge,proto3" json:"has_badge,omitempty"`
	IssuedDate    uint64                 `protobuf:"varint,4,opt,name=issued_date,json=issuedDate,proto3" json:"issued_date,omitempty"`
	BadgeType     string                 `protobuf:"bytes,5,opt,name=badge_type,json=badgeType,proto3" json:"badge_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBadge) Reset() {
	*x = UserBadge{}
	mi := &file_marketplace_badge_v1_user_badge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBadge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBadge) ProtoMessage() {}

func (x *UserBadge) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_badge_v1_user_badge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBadge.ProtoReflect.Descriptor instead.
func (*UserBadge) Descriptor() ([]byte, []int) {
	return file_marketplace_badge_v1_user_badge_proto_rawDescGZIP(), []int{0}
}

func (x *UserBadge) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *UserBadge) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UserBadge) GetHasBadge() bool {
	if x != nil {
		return x.HasBadge
	}
	return false
}

func (x *UserBadge) GetIssuedDate() uint64 {
	if x != nil {
		return x.IssuedDate
	}
	return 0
}

func (x *UserBadge) GetBadgeType() string {
	if x != nil {
		return x.BadgeType
	}
	return ""
}

var File_marketplace_badge_v1_user_badge_proto protoreflect.FileDescriptor

const file_marketplace_badge_v1_user_badge_proto_rawDesc = "" +
	"\n" +
	"%marketplace/badge/v1/user_badge.proto\x12\x14marketplace.badge.v1\"\x98\x01\n" +
	"\tUserBadge\x12\x14\n" +
	"\x05index\x18\x01 \x01(\tR\x05index\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1b\n" +
	"\thas_badge\x18\x03 \x01(\bR\bhasBadge\x12\x1f\n" +
	"\vissued_date\x18\x04 \x01(\x04R\n" +
	"issuedDate\x12\x1d\n" +
	"\n" +
	"badge_type\x18\x05 \x01(\tR\tbadgeTypeB*Z(github.com/tmp/marketplace/x/badge/typesb\x06proto3"

var (
	file_marketplace_badge_v1_user_badge_proto_rawDescOnce sync.Once
	file_marketplace_badge_v1_user_badge_proto_rawDescData []byte
)

func file_marketplace_badge_v1_user_badge_proto_rawDescGZIP() []byte {
	file_marketplace_badge_v1_user_badge_proto_rawDescOnce.Do(func() {
		file_marketplace_badge_v1_user_badge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketplace_badge_v1_user_badge_proto_rawDesc), len(file_marketplace_badge_v1_user_badge_proto_rawDesc)))
	})
	return file_marketplace_badge_v1_user_badge_proto_rawDescData
}

var file_marketplace_badge_v1_user_badge_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_marketplace_badge_v1_user_badge_proto_goTypes = []any{
	(*UserBadge)(nil), // 0: marketplace.badge.v1.UserBadge
}
var file_marketplace_badge_v1_user_badge_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_marketplace_badge_v1_user_badge_proto_init() }
func file_marketplace_badge_v1_user_badge_proto_init() {
	if File_marketplace_badge_v1_user_badge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketplace_badge_v1_user_badge_proto_rawDesc), len(file_marketplace_badge_v1_user_badge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_marketplace_badge_v1_user_badge_proto_goTypes,
		DependencyIndexes: file_marketplace_badge_v1_user_badge_proto_depIdxs,
		MessageInfos:      file_marketplace_badge_v1_user_badge_proto_msgTypes,
	}.Build()
	File_marketplace_badge_v1_user_badge_proto = out.File
	file_marketplace_badge_v1_user_badge_proto_goTypes = nil
	file_marketplace_badge_v1_user_badge_proto_depIdxs = nil
}
