// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: marketplace/badge/v1/tx.proto

package types

import (
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// NOTE: All parameters must be supplied.
	Params        *Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParams) Reset() {
	*x = MsgUpdateParams{}
	mi := &file_marketplace_badge_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParams) ProtoMessage() {}

func (x *MsgUpdateParams) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_badge_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParams.ProtoReflect.Descriptor instead.
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return file_marketplace_badge_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgUpdateParams) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgUpdateParams) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParamsResponse) Reset() {
	*x = MsgUpdateParamsResponse{}
	mi := &file_marketplace_badge_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParamsResponse) ProtoMessage() {}

func (x *MsgUpdateParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_badge_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParamsResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_badge_v1_tx_proto_rawDescGZIP(), []int{1}
}

// MsgIssueBadge defines the MsgIssueBadge message.
type MsgIssueBadge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creator       string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Recipient     string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	BadgeType     string                 `protobuf:"bytes,3,opt,name=badge_type,json=badgeType,proto3" json:"badge_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgIssueBadge) Reset() {
	*x = MsgIssueBadge{}
	mi := &file_marketplace_badge_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgIssueBadge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgIssueBadge) ProtoMessage() {}

func (x *MsgIssueBadge) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_badge_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgIssueBadge.ProtoReflect.Descriptor instead.
func (*MsgIssueBadge) Descriptor() ([]byte, []int) {
	return file_marketplace_badge_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgIssueBadge) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgIssueBadge) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *MsgIssueBadge) GetBadgeType() string {
	if x != nil {
		return x.BadgeType
	}
	return ""
}

// MsgIssueBadgeResponse defines the MsgIssueBadgeResponse message.
type MsgIssueBadgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgIssueBadgeResponse) Reset() {
	*x = MsgIssueBadgeResponse{}
	mi := &file_marketplace_badge_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgIssueBadgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgIssueBadgeResponse) ProtoMessage() {}

func (x *MsgIssueBadgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_badge_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgIssueBadgeResponse.ProtoReflect.Descriptor instead.
func (*MsgIssueBadgeResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_badge_v1_tx_proto_rawDescGZIP(), []int{3}
}

var File_marketplace_badge_v1_tx_proto protoreflect.FileDescriptor

const file_marketplace_badge_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x1dmarketplace/badge/v1/tx.proto\x12\x14marketplace.badge.v1\x1a\x11amino/amino.proto\x1a\x17cosmos/msg/v1/msg.proto\x1a\x19cosmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\x1a!marketplace/badge/v1/params.proto\"\xc2\x01\n" +
	"\x0fMsgUpdateParams\x126\n" +
	"\tauthority\x18\x01 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\tauthority\x12?\n" +
	"\x06params\x18\x02 \x01(\v2\x1c.marketplace.badge.v1.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params:6\x82\xe7\xb0*\tauthority\x8a\xe7\xb0*#marketplace/x/badge/MsgUpdateParams\"\x19\n" +
	"\x17MsgUpdateParamsResponse\"\x8e\x01\n" +
	"\rMsgIssueBadge\x122\n" +
	"\acreator\x18\x01 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\acreator\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x1d\n" +
	"\n" +
	"badge_type\x18\x03 \x01(\tR\tbadgeType:\f\x82\xe7\xb0*\acreator\"\x17\n" +
	"\x15MsgIssueBadgeResponse2\xd2\x01\n" +
	"\x03Msg\x12d\n" +
	"\fUpdateParams\x12%.marketplace.badge.v1.MsgUpdateParams\x1a-.marketplace.badge.v1.MsgUpdateParamsResponse\x12^\n" +
	"\n" +
	"IssueBadge\x12#.marketplace.badge.v1.MsgIssueBadge\x1a+.marketplace.badge.v1.MsgIssueBadgeResponse\x1a\x05\x80\xe7\xb0*\x01B*Z(github.com/tmp/marketplace/x/badge/typesb\x06proto3"

var (
	file_marketplace_badge_v1_tx_proto_rawDescOnce sync.Once
	file_marketplace_badge_v1_tx_proto_rawDescData []byte
)

func file_marketplace_badge_v1_tx_proto_rawDescGZIP() []byte {
	file_marketplace_badge_v1_tx_proto_rawDescOnce.Do(func() {
		file_marketplace_badge_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketplace_badge_v1_tx_proto_rawDesc), len(file_marketplace_badge_v1_tx_proto_rawDesc)))
	})
	return file_marketplace_badge_v1_tx_proto_rawDescData
}

var file_marketplace_badge_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_marketplace_badge_v1_tx_proto_goTypes = []any{
	(*MsgUpdateParams)(nil),         // 0: marketplace.badge.v1.MsgUpdateParams
	(*MsgUpdateParamsResponse)(nil), // 1: marketplace.badge.v1.MsgUpdateParamsResponse
	(*MsgIssueBadge)(nil),           // 2: marketplace.badge.v1.MsgIssueBadge
	(*MsgIssueBadgeResponse)(nil),   // 3: marketplace.badge.v1.MsgIssueBadgeResponse
	(*Params)(nil),                  // 4: marketplace.badge.v1.Params
}
var file_marketplace_badge_v1_tx_proto_depIdxs = []int32{
	4, // 0: marketplace.badge.v1.MsgUpdateParams.params:type_name -> marketplace.badge.v1.Params
	0, // 1: marketplace.badge.v1.Msg.UpdateParams:input_type -> marketplace.badge.v1.MsgUpdateParams
	2, // 2: marketplace.badge.v1.Msg.IssueBadge:input_type -> marketplace.badge.v1.MsgIssueBadge
	1, // 3: marketplace.badge.v1.Msg.UpdateParams:output_type -> marketplace.badge.v1.MsgUpdateParamsResponse
	3, // 4: marketplace.badge.v1.Msg.IssueBadge:output_type -> marketplace.badge.v1.MsgIssueBadgeResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_marketplace_badge_v1_tx_proto_init() }
func file_marketplace_badge_v1_tx_proto_init() {
	if File_marketplace_badge_v1_tx_proto != nil {
		return
	}
	file_marketplace_badge_v1_params_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketplace_badge_v1_tx_proto_rawDesc), len(file_marketplace_badge_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marketplace_badge_v1_tx_proto_goTypes,
		DependencyIndexes: file_marketplace_badge_v1_tx_proto_depIdxs,
		MessageInfos:      file_marketplace_badge_v1_tx_proto_msgTypes,
	}.Build()
	File_marketplace_badge_v1_tx_proto = out.File
	file_marketplace_badge_v1_tx_proto_goTypes = nil
	file_marketplace_badge_v1_tx_proto_depIdxs = nil
}
