// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: marketplace/mlcoin/v1/emission_state.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EmissionState defines the EmissionState message.
type EmissionState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalSupply   uint64                 `protobuf:"varint,1,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`
	Circulating   uint64                 `protobuf:"varint,2,opt,name=circulating,proto3" json:"circulating,omitempty"`
	MonthlyCap    uint64                 `protobuf:"varint,3,opt,name=monthly_cap,json=monthlyCap,proto3" json:"monthly_cap,omitempty"`
	DailyLimit    uint64                 `protobuf:"varint,4,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	CurrentMonth  uint64                 `protobuf:"varint,5,opt,name=current_month,json=currentMonth,proto3" json:"current_month,omitempty"`
	CurrentDay    uint64                 `protobuf:"varint,6,opt,name=current_day,json=currentDay,proto3" json:"current_day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmissionState) Reset() {
	*x = EmissionState{}
	mi := &file_marketplace_mlcoin_v1_emission_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmissionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmissionState) ProtoMessage() {}

func (x *EmissionState) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mlcoin_v1_emission_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmissionState.ProtoReflect.Descriptor instead.
func (*EmissionState) Descriptor() ([]byte, []int) {
	return file_marketplace_mlcoin_v1_emission_state_proto_rawDescGZIP(), []int{0}
}

func (x *EmissionState) GetTotalSupply() uint64 {
	if x != nil {
		return x.TotalSupply
	}
	return 0
}

func (x *EmissionState) GetCirculating() uint64 {
	if x != nil {
		return x.Circulating
	}
	return 0
}

func (x *EmissionState) GetMonthlyCap() uint64 {
	if x != nil {
		return x.MonthlyCap
	}
	return 0
}

func (x *EmissionState) GetDailyLimit() uint64 {
	if x != nil {
		return x.DailyLimit
	}
	return 0
}

func (x *EmissionState) GetCurrentMonth() uint64 {
	if x != nil {
		return x.CurrentMonth
	}
	return 0
}

func (x *EmissionState) GetCurrentDay() uint64 {
	if x != nil {
		return x.CurrentDay
	}
	return 0
}

var File_marketplace_mlcoin_v1_emission_state_proto protoreflect.FileDescriptor

const file_marketplace_mlcoin_v1_emission_state_proto_rawDesc = "" +
	"\n" +
	"*marketplace/mlcoin/v1/emission_state.proto\x12\x15marketplace.mlcoin.v1\"\xdc\x01\n" +
	"\rEmissionState\x12!\n" +
	"\ftotal_supply\x18\x01 \x01(\x04R\vtotalSupply\x12 \n" +
	"\vcirculating\x18\x02 \x01(\x04R\vcirculating\x12\x1f\n" +
	"\vmonthly_cap\x18\x03 \x01(\x04R\n" +
	"monthlyCap\x12\x1f\n" +
	"\vdaily_limit\x18\x04 \x01(\x04R\n" +
	"dailyLimit\x12#\n" +
	"\rcurrent_month\x18\x05 \x01(\x04R\fcurrentMonth\x12\x1f\n" +
	"\vcurrent_day\x18\x06 \x01(\x04R\n" +
	"currentDayB+Z)github.com/tmp/marketplace/x/mlcoin/typesb\x06proto3"

var (
	file_marketplace_mlcoin_v1_emission_state_proto_rawDescOnce sync.Once
	file_marketplace_mlcoin_v1_emission_state_proto_rawDescData []byte
)

func file_marketplace_mlcoin_v1_emission_state_proto_rawDescGZIP() []byte {
	file_marketplace_mlcoin_v1_emission_state_proto_rawDescOnce.Do(func() {
		file_marketplace_mlcoin_v1_emission_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketplace_mlcoin_v1_emission_state_proto_rawDesc), len(file_marketplace_mlcoin_v1_emission_state_proto_rawDesc)))
	})
	return file_marketplace_mlcoin_v1_emission_state_proto_rawDescData
}

var file_marketplace_mlcoin_v1_emission_state_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_marketplace_mlcoin_v1_emission_state_proto_goTypes = []any{
	(*EmissionState)(nil), // 0: marketplace.mlcoin.v1.EmissionState
}
var file_marketplace_mlcoin_v1_emission_state_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_marketplace_mlcoin_v1_emission_state_proto_init() }
func file_marketplace_mlcoin_v1_emission_state_proto_init() {
	if File_marketplace_mlcoin_v1_emission_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketplace_mlcoin_v1_emission_state_proto_rawDesc), len(file_marketplace_mlcoin_v1_emission_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_marketplace_mlcoin_v1_emission_state_proto_goTypes,
		DependencyIndexes: file_marketplace_mlcoin_v1_emission_state_proto_depIdxs,
		MessageInfos:      file_marketplace_mlcoin_v1_emission_state_proto_msgTypes,
	}.Build()
	File_marketplace_mlcoin_v1_emission_state_proto = out.File
	file_marketplace_mlcoin_v1_emission_state_proto_goTypes = nil
	file_marketplace_mlcoin_v1_emission_state_proto_depIdxs = nil
}
