// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: marketplace/mlcoin/v1/treasury.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TreasuryQuery_TreasuryMetrics_FullMethodName = "/marketplace.mlcoin.v1.TreasuryQuery/TreasuryMetrics"
	TreasuryQuery_TreasuryHistory_FullMethodName = "/marketplace.mlcoin.v1.TreasuryQuery/TreasuryHistory"
)

// TreasuryQueryClient is the client API for TreasuryQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TreasuryQueryClient interface {
	TreasuryMetrics(ctx context.Context, in *QueryTreasuryRequest, opts ...grpc.CallOption) (*QueryTreasuryResponse, error)
	TreasuryHistory(ctx context.Context, in *QueryTreasuryHistoryRequest, opts ...grpc.CallOption) (*QueryTreasuryHistoryResponse, error)
}

type treasuryQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewTreasuryQueryClient(cc grpc.ClientConnInterface) TreasuryQueryClient {
	return &treasuryQueryClient{cc}
}

func (c *treasuryQueryClient) TreasuryMetrics(ctx context.Context, in *QueryTreasuryRequest, opts ...grpc.CallOption) (*QueryTreasuryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryTreasuryResponse)
	err := c.cc.Invoke(ctx, TreasuryQuery_TreasuryMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treasuryQueryClient) TreasuryHistory(ctx context.Context, in *QueryTreasuryHistoryRequest, opts ...grpc.CallOption) (*QueryTreasuryHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryTreasuryHistoryResponse)
	err := c.cc.Invoke(ctx, TreasuryQuery_TreasuryHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TreasuryQueryServer is the server API for TreasuryQuery service.
// All implementations must embed UnimplementedTreasuryQueryServer
// for forward compatibility.
type TreasuryQueryServer interface {
	TreasuryMetrics(context.Context, *QueryTreasuryRequest) (*QueryTreasuryResponse, error)
	TreasuryHistory(context.Context, *QueryTreasuryHistoryRequest) (*QueryTreasuryHistoryResponse, error)
	mustEmbedUnimplementedTreasuryQueryServer()
}

// UnimplementedTreasuryQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTreasuryQueryServer struct{}

func (UnimplementedTreasuryQueryServer) TreasuryMetrics(context.Context, *QueryTreasuryRequest) (*QueryTreasuryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TreasuryMetrics not implemented")
}
func (UnimplementedTreasuryQueryServer) TreasuryHistory(context.Context, *QueryTreasuryHistoryRequest) (*QueryTreasuryHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TreasuryHistory not implemented")
}
func (UnimplementedTreasuryQueryServer) mustEmbedUnimplementedTreasuryQueryServer() {}
func (UnimplementedTreasuryQueryServer) testEmbeddedByValue()                       {}

// UnsafeTreasuryQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TreasuryQueryServer will
// result in compilation errors.
type UnsafeTreasuryQueryServer interface {
	mustEmbedUnimplementedTreasuryQueryServer()
}

func RegisterTreasuryQueryServer(s grpc.ServiceRegistrar, srv TreasuryQueryServer) {
	// If the following call panics, it indicates UnimplementedTreasuryQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TreasuryQuery_ServiceDesc, srv)
}

func _TreasuryQuery_TreasuryMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTreasuryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreasuryQueryServer).TreasuryMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreasuryQuery_TreasuryMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreasuryQueryServer).TreasuryMetrics(ctx, req.(*QueryTreasuryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreasuryQuery_TreasuryHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTreasuryHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreasuryQueryServer).TreasuryHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreasuryQuery_TreasuryHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreasuryQueryServer).TreasuryHistory(ctx, req.(*QueryTreasuryHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TreasuryQuery_ServiceDesc is the grpc.ServiceDesc for TreasuryQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TreasuryQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marketplace.mlcoin.v1.TreasuryQuery",
	HandlerType: (*TreasuryQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TreasuryMetrics",
			Handler:    _TreasuryQuery_TreasuryMetrics_Handler,
		},
		{
			MethodName: "TreasuryHistory",
			Handler:    _TreasuryQuery_TreasuryHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "marketplace/mlcoin/v1/treasury.proto",
}
