// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: marketplace/mlcoin/v1/market.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MarketPrice tracks current buy/sell prices and trading volume
type MarketPrice struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// buy_price is the current price to buy 1 MLCN in KES (scaled by 100, e.g., 62 = 0.62 KES)
	BuyPrice uint64 `protobuf:"varint,1,opt,name=buy_price,json=buyPrice,proto3" json:"buy_price,omitempty"`
	// sell_price is the current price to sell 1 MLCN in KES (scaled by 100, e.g., 58 = 0.58 KES)
	SellPrice uint64 `protobuf:"varint,2,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`
	// total_buy_volume tracks total MLCN bought
	TotalBuyVolume uint64 `protobuf:"varint,3,opt,name=total_buy_volume,json=totalBuyVolume,proto3" json:"total_buy_volume,omitempty"`
	// total_sell_volume tracks total MLCN sold
	TotalSellVolume uint64 `protobuf:"varint,4,opt,name=total_sell_volume,json=totalSellVolume,proto3" json:"total_sell_volume,omitempty"`
	// last_update_height is the block height of last price update
	LastUpdateHeight uint64 `protobuf:"varint,5,opt,name=last_update_height,json=lastUpdateHeight,proto3" json:"last_update_height,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MarketPrice) Reset() {
	*x = MarketPrice{}
	mi := &file_marketplace_mlcoin_v1_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketPrice) ProtoMessage() {}

func (x *MarketPrice) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mlcoin_v1_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketPrice.ProtoReflect.Descriptor instead.
func (*MarketPrice) Descriptor() ([]byte, []int) {
	return file_marketplace_mlcoin_v1_market_proto_rawDescGZIP(), []int{0}
}

func (x *MarketPrice) GetBuyPrice() uint64 {
	if x != nil {
		return x.BuyPrice
	}
	return 0
}

func (x *MarketPrice) GetSellPrice() uint64 {
	if x != nil {
		return x.SellPrice
	}
	return 0
}

func (x *MarketPrice) GetTotalBuyVolume() uint64 {
	if x != nil {
		return x.TotalBuyVolume
	}
	return 0
}

func (x *MarketPrice) GetTotalSellVolume() uint64 {
	if x != nil {
		return x.TotalSellVolume
	}
	return 0
}

func (x *MarketPrice) GetLastUpdateHeight() uint64 {
	if x != nil {
		return x.LastUpdateHeight
	}
	return 0
}

// KesBalance tracks user's KES balance for marketplace
type KesBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance       uint64                 `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"` // KES balance scaled by 100 (e.g., 10000 = 100.00 KES)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KesBalance) Reset() {
	*x = KesBalance{}
	mi := &file_marketplace_mlcoin_v1_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KesBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KesBalance) ProtoMessage() {}

func (x *KesBalance) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mlcoin_v1_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KesBalance.ProtoReflect.Descriptor instead.
func (*KesBalance) Descriptor() ([]byte, []int) {
	return file_marketplace_mlcoin_v1_market_proto_rawDescGZIP(), []int{1}
}

func (x *KesBalance) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *KesBalance) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

// Trade represents a completed buy/sell order
type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Trader        string                 `protobuf:"bytes,2,opt,name=trader,proto3" json:"trader,omitempty"`
	TradeType     string                 `protobuf:"bytes,3,opt,name=trade_type,json=tradeType,proto3" json:"trade_type,omitempty"` // "buy" or "sell"
	MlcnAmount    uint64                 `protobuf:"varint,4,opt,name=mlcn_amount,json=mlcnAmount,proto3" json:"mlcn_amount,omitempty"`
	KesAmount     uint64                 `protobuf:"varint,5,opt,name=kes_amount,json=kesAmount,proto3" json:"kes_amount,omitempty"`
	Price         uint64                 `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"` // Price at time of trade
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BlockHeight   uint64                 `protobuf:"varint,8,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_marketplace_mlcoin_v1_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mlcoin_v1_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_marketplace_mlcoin_v1_market_proto_rawDescGZIP(), []int{2}
}

func (x *Trade) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *Trade) GetTrader() string {
	if x != nil {
		return x.Trader
	}
	return ""
}

func (x *Trade) GetTradeType() string {
	if x != nil {
		return x.TradeType
	}
	return ""
}

func (x *Trade) GetMlcnAmount() uint64 {
	if x != nil {
		return x.MlcnAmount
	}
	return 0
}

func (x *Trade) GetKesAmount() uint64 {
	if x != nil {
		return x.KesAmount
	}
	return 0
}

func (x *Trade) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Trade) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

// CurrencyRate represents exchange rate of a currency to KES (scaled by 100)
type CurrencyRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`                           // ISO code, e.g., "USD"
	RateToKes     uint64                 `protobuf:"varint,2,opt,name=rate_to_kes,json=rateToKes,proto3" json:"rate_to_kes,omitempty"`     // 1 unit of currency equals rate_to_kes / 100 KES
	LastUpdated   uint64                 `protobuf:"varint,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"` // block height
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyRate) Reset() {
	*x = CurrencyRate{}
	mi := &file_marketplace_mlcoin_v1_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyRate) ProtoMessage() {}

func (x *CurrencyRate) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mlcoin_v1_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyRate.ProtoReflect.Descriptor instead.
func (*CurrencyRate) Descriptor() ([]byte, []int) {
	return file_marketplace_mlcoin_v1_market_proto_rawDescGZIP(), []int{3}
}

func (x *CurrencyRate) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CurrencyRate) GetRateToKes() uint64 {
	if x != nil {
		return x.RateToKes
	}
	return 0
}

func (x *CurrencyRate) GetLastUpdated() uint64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

var File_marketplace_mlcoin_v1_market_proto protoreflect.FileDescriptor

const file_marketplace_mlcoin_v1_market_proto_rawDesc = "" +
	"\n" +
	"\"marketplace/mlcoin/v1/market.proto\x12\x15marketplace.mlcoin.v1\"\xcd\x01\n" +
	"\vMarketPrice\x12\x1b\n" +
	"\tbuy_price\x18\x01 \x01(\x04R\bbuyPrice\x12\x1d\n" +
	"\n" +
	"sell_price\x18\x02 \x01(\x04R\tsellPrice\x12(\n" +
	"\x10total_buy_volume\x18\x03 \x01(\x04R\x0etotalBuyVolume\x12*\n" +
	"\x11total_sell_volume\x18\x04 \x01(\x04R\x0ftotalSellVolume\x12,\n" +
	"\x12last_update_height\x18\x05 \x01(\x04R\x10lastUpdateHeight\"@\n" +
	"\n" +
	"KesBalance\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x04R\abalance\"\xea\x01\n" +
	"\x05Trade\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x16\n" +
	"\x06trader\x18\x02 \x01(\tR\x06trader\x12\x1d\n" +
	"\n" +
	"trade_type\x18\x03 \x01(\tR\ttradeType\x12\x1f\n" +
	"\vmlcn_amount\x18\x04 \x01(\x04R\n" +
	"mlcnAmount\x12\x1d\n" +
	"\n" +
	"kes_amount\x18\x05 \x01(\x04R\tkesAmount\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x04R\x05price\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12!\n" +
	"\fblock_height\x18\b \x01(\x04R\vblockHeight\"m\n" +
	"\fCurrencyRate\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x1e\n" +
	"\vrate_to_kes\x18\x02 \x01(\x04R\trateToKes\x12!\n" +
	"\flast_updated\x18\x03 \x01(\x04R\vlastUpdatedB+Z)github.com/tmp/marketplace/x/mlcoin/typesb\x06proto3"

var (
	file_marketplace_mlcoin_v1_market_proto_rawDescOnce sync.Once
	file_marketplace_mlcoin_v1_market_proto_rawDescData []byte
)

func file_marketplace_mlcoin_v1_market_proto_rawDescGZIP() []byte {
	file_marketplace_mlcoin_v1_market_proto_rawDescOnce.Do(func() {
		file_marketplace_mlcoin_v1_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketplace_mlcoin_v1_market_proto_rawDesc), len(file_marketplace_mlcoin_v1_market_proto_rawDesc)))
	})
	return file_marketplace_mlcoin_v1_market_proto_rawDescData
}

var file_marketplace_mlcoin_v1_market_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_marketplace_mlcoin_v1_market_proto_goTypes = []any{
	(*MarketPrice)(nil),  // 0: marketplace.mlcoin.v1.MarketPrice
	(*KesBalance)(nil),   // 1: marketplace.mlcoin.v1.KesBalance
	(*Trade)(nil),        // 2: marketplace.mlcoin.v1.Trade
	(*CurrencyRate)(nil), // 3: marketplace.mlcoin.v1.CurrencyRate
}
var file_marketplace_mlcoin_v1_market_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_marketplace_mlcoin_v1_market_proto_init() }
func file_marketplace_mlcoin_v1_market_proto_init() {
	if File_marketplace_mlcoin_v1_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketplace_mlcoin_v1_market_proto_rawDesc), len(file_marketplace_mlcoin_v1_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_marketplace_mlcoin_v1_market_proto_goTypes,
		DependencyIndexes: file_marketplace_mlcoin_v1_market_proto_depIdxs,
		MessageInfos:      file_marketplace_mlcoin_v1_market_proto_msgTypes,
	}.Build()
	File_marketplace_mlcoin_v1_market_proto = out.File
	file_marketplace_mlcoin_v1_market_proto_goTypes = nil
	file_marketplace_mlcoin_v1_market_proto_depIdxs = nil
}
