// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: marketplace/mlcoin/v1/tx.proto

package types

import (
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Admin: set currency rate (rate is scaled by 100, e.g., 13745 = 137.45 KES)
type MsgSetCurrencyRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	RateToKes     uint64                 `protobuf:"varint,3,opt,name=rate_to_kes,json=rateToKes,proto3" json:"rate_to_kes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSetCurrencyRate) Reset() {
	*x = MsgSetCurrencyRate{}
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSetCurrencyRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSetCurrencyRate) ProtoMessage() {}

func (x *MsgSetCurrencyRate) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSetCurrencyRate.ProtoReflect.Descriptor instead.
func (*MsgSetCurrencyRate) Descriptor() ([]byte, []int) {
	return file_marketplace_mlcoin_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgSetCurrencyRate) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgSetCurrencyRate) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *MsgSetCurrencyRate) GetRateToKes() uint64 {
	if x != nil {
		return x.RateToKes
	}
	return 0
}

type MsgSetCurrencyRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSetCurrencyRateResponse) Reset() {
	*x = MsgSetCurrencyRateResponse{}
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSetCurrencyRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSetCurrencyRateResponse) ProtoMessage() {}

func (x *MsgSetCurrencyRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSetCurrencyRateResponse.ProtoReflect.Descriptor instead.
func (*MsgSetCurrencyRateResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_mlcoin_v1_tx_proto_rawDescGZIP(), []int{1}
}

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// NOTE: All parameters must be supplied.
	Params        *Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParams) Reset() {
	*x = MsgUpdateParams{}
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParams) ProtoMessage() {}

func (x *MsgUpdateParams) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParams.ProtoReflect.Descriptor instead.
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return file_marketplace_mlcoin_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgUpdateParams) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgUpdateParams) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParamsResponse) Reset() {
	*x = MsgUpdateParamsResponse{}
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParamsResponse) ProtoMessage() {}

func (x *MsgUpdateParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParamsResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_mlcoin_v1_tx_proto_rawDescGZIP(), []int{3}
}

// MsgTransferMallcoin defines the MsgTransferMallcoin message.
type MsgTransferMallcoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creator       string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgTransferMallcoin) Reset() {
	*x = MsgTransferMallcoin{}
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgTransferMallcoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgTransferMallcoin) ProtoMessage() {}

func (x *MsgTransferMallcoin) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgTransferMallcoin.ProtoReflect.Descriptor instead.
func (*MsgTransferMallcoin) Descriptor() ([]byte, []int) {
	return file_marketplace_mlcoin_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgTransferMallcoin) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgTransferMallcoin) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *MsgTransferMallcoin) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

// MsgTransferMallcoinResponse defines the MsgTransferMallcoinResponse message.
type MsgTransferMallcoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"` // Unique transaction ID generated for this transfer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgTransferMallcoinResponse) Reset() {
	*x = MsgTransferMallcoinResponse{}
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgTransferMallcoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgTransferMallcoinResponse) ProtoMessage() {}

func (x *MsgTransferMallcoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgTransferMallcoinResponse.ProtoReflect.Descriptor instead.
func (*MsgTransferMallcoinResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_mlcoin_v1_tx_proto_rawDescGZIP(), []int{5}
}

func (x *MsgTransferMallcoinResponse) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

// MsgBuyMallcoin defines the message for buying Mallcoins with KES.
type MsgBuyMallcoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buyer         string                 `protobuf:"bytes,1,opt,name=buyer,proto3" json:"buyer,omitempty"`
	MlcnAmount    uint64                 `protobuf:"varint,2,opt,name=mlcn_amount,json=mlcnAmount,proto3" json:"mlcn_amount,omitempty"` // Amount of MLCN to buy
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgBuyMallcoin) Reset() {
	*x = MsgBuyMallcoin{}
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgBuyMallcoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBuyMallcoin) ProtoMessage() {}

func (x *MsgBuyMallcoin) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBuyMallcoin.ProtoReflect.Descriptor instead.
func (*MsgBuyMallcoin) Descriptor() ([]byte, []int) {
	return file_marketplace_mlcoin_v1_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MsgBuyMallcoin) GetBuyer() string {
	if x != nil {
		return x.Buyer
	}
	return ""
}

func (x *MsgBuyMallcoin) GetMlcnAmount() uint64 {
	if x != nil {
		return x.MlcnAmount
	}
	return 0
}

// MsgBuyMallcoinResponse defines the response for buying Mallcoins.
type MsgBuyMallcoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`  // Unique trade ID
	KesPaid       uint64                 `protobuf:"varint,2,opt,name=kes_paid,json=kesPaid,proto3" json:"kes_paid,omitempty"` // Total KES paid
	Price         uint64                 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`                    // Price per MLCN at time of purchase
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgBuyMallcoinResponse) Reset() {
	*x = MsgBuyMallcoinResponse{}
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgBuyMallcoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBuyMallcoinResponse) ProtoMessage() {}

func (x *MsgBuyMallcoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBuyMallcoinResponse.ProtoReflect.Descriptor instead.
func (*MsgBuyMallcoinResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_mlcoin_v1_tx_proto_rawDescGZIP(), []int{7}
}

func (x *MsgBuyMallcoinResponse) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *MsgBuyMallcoinResponse) GetKesPaid() uint64 {
	if x != nil {
		return x.KesPaid
	}
	return 0
}

func (x *MsgBuyMallcoinResponse) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// MsgSellMallcoin defines the message for selling Mallcoins for KES.
type MsgSellMallcoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seller        string                 `protobuf:"bytes,1,opt,name=seller,proto3" json:"seller,omitempty"`
	MlcnAmount    uint64                 `protobuf:"varint,2,opt,name=mlcn_amount,json=mlcnAmount,proto3" json:"mlcn_amount,omitempty"` // Amount of MLCN to sell
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSellMallcoin) Reset() {
	*x = MsgSellMallcoin{}
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSellMallcoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSellMallcoin) ProtoMessage() {}

func (x *MsgSellMallcoin) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSellMallcoin.ProtoReflect.Descriptor instead.
func (*MsgSellMallcoin) Descriptor() ([]byte, []int) {
	return file_marketplace_mlcoin_v1_tx_proto_rawDescGZIP(), []int{8}
}

func (x *MsgSellMallcoin) GetSeller() string {
	if x != nil {
		return x.Seller
	}
	return ""
}

func (x *MsgSellMallcoin) GetMlcnAmount() uint64 {
	if x != nil {
		return x.MlcnAmount
	}
	return 0
}

// MsgSellMallcoinResponse defines the response for selling Mallcoins.
type MsgSellMallcoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`              // Unique trade ID
	KesReceived   uint64                 `protobuf:"varint,2,opt,name=kes_received,json=kesReceived,proto3" json:"kes_received,omitempty"` // Total KES received
	Price         uint64                 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`                                // Price per MLCN at time of sale
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSellMallcoinResponse) Reset() {
	*x = MsgSellMallcoinResponse{}
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSellMallcoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSellMallcoinResponse) ProtoMessage() {}

func (x *MsgSellMallcoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSellMallcoinResponse.ProtoReflect.Descriptor instead.
func (*MsgSellMallcoinResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_mlcoin_v1_tx_proto_rawDescGZIP(), []int{9}
}

func (x *MsgSellMallcoinResponse) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *MsgSellMallcoinResponse) GetKesReceived() uint64 {
	if x != nil {
		return x.KesReceived
	}
	return 0
}

func (x *MsgSellMallcoinResponse) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// MintMallcoin allows an authority to mint MLCN to a recipient address.
type MsgMintMallcoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Recipient     string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgMintMallcoin) Reset() {
	*x = MsgMintMallcoin{}
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgMintMallcoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgMintMallcoin) ProtoMessage() {}

func (x *MsgMintMallcoin) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgMintMallcoin.ProtoReflect.Descriptor instead.
func (*MsgMintMallcoin) Descriptor() ([]byte, []int) {
	return file_marketplace_mlcoin_v1_tx_proto_rawDescGZIP(), []int{10}
}

func (x *MsgMintMallcoin) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgMintMallcoin) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *MsgMintMallcoin) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type MsgMintMallcoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"` // Tx id for the mint operation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgMintMallcoinResponse) Reset() {
	*x = MsgMintMallcoinResponse{}
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgMintMallcoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgMintMallcoinResponse) ProtoMessage() {}

func (x *MsgMintMallcoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_mlcoin_v1_tx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgMintMallcoinResponse.ProtoReflect.Descriptor instead.
func (*MsgMintMallcoinResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_mlcoin_v1_tx_proto_rawDescGZIP(), []int{11}
}

func (x *MsgMintMallcoinResponse) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

var File_marketplace_mlcoin_v1_tx_proto protoreflect.FileDescriptor

const file_marketplace_mlcoin_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x1emarketplace/mlcoin/v1/tx.proto\x12\x15marketplace.mlcoin.v1\x1a\x11amino/amino.proto\x1a\x17cosmos/msg/v1/msg.proto\x1a\x19cosmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\x1a\"marketplace/mlcoin/v1/params.proto\"\x98\x01\n" +
	"\x12MsgSetCurrencyRate\x126\n" +
	"\tauthority\x18\x01 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\tauthority\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x1e\n" +
	"\vrate_to_kes\x18\x03 \x01(\x04R\trateToKes:\x0e\x82\xe7\xb0*\tauthority\"\x1c\n" +
	"\x1aMsgSetCurrencyRateResponse\"\xc4\x01\n" +
	"\x0fMsgUpdateParams\x126\n" +
	"\tauthority\x18\x01 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\tauthority\x12@\n" +
	"\x06params\x18\x02 \x01(\v2\x1d.marketplace.mlcoin.v1.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params:7\x82\xe7\xb0*\tauthority\x8a\xe7\xb0*$marketplace/x/mlcoin/MsgUpdateParams\"\x19\n" +
	"\x17MsgUpdateParamsResponse\"\x7f\n" +
	"\x13MsgTransferMallcoin\x122\n" +
	"\acreator\x18\x01 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\acreator\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to:\f\x82\xe7\xb0*\acreator\"2\n" +
	"\x1bMsgTransferMallcoinResponse\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\"m\n" +
	"\x0eMsgBuyMallcoin\x12.\n" +
	"\x05buyer\x18\x01 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\x05buyer\x12\x1f\n" +
	"\vmlcn_amount\x18\x02 \x01(\x04R\n" +
	"mlcnAmount:\n" +
	"\x82\xe7\xb0*\x05buyer\"d\n" +
	"\x16MsgBuyMallcoinResponse\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12\x19\n" +
	"\bkes_paid\x18\x02 \x01(\x04R\akesPaid\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x04R\x05price\"q\n" +
	"\x0fMsgSellMallcoin\x120\n" +
	"\x06seller\x18\x01 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\x06seller\x12\x1f\n" +
	"\vmlcn_amount\x18\x02 \x01(\x04R\n" +
	"mlcnAmount:\v\x82\xe7\xb0*\x06seller\"m\n" +
	"\x17MsgSellMallcoinResponse\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12!\n" +
	"\fkes_received\x18\x02 \x01(\x04R\vkesReceived\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x04R\x05price\"\xa9\x01\n" +
	"\x0fMsgMintMallcoin\x126\n" +
	"\tauthority\x18\x01 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\tauthority\x126\n" +
	"\trecipient\x18\x02 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\trecipient\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount:\x0e\x82\xe7\xb0*\tauthority\".\n" +
	"\x17MsgMintMallcoinResponse\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId2\x9d\x04\n" +
	"\x03Msg\x12f\n" +
	"\fUpdateParams\x12&.marketplace.mlcoin.v1.MsgUpdateParams\x1a..marketplace.mlcoin.v1.MsgUpdateParamsResponse\x12r\n" +
	"\x10TransferMallcoin\x12*.marketplace.mlcoin.v1.MsgTransferMallcoin\x1a2.marketplace.mlcoin.v1.MsgTransferMallcoinResponse\x12c\n" +
	"\vBuyMallcoin\x12%.marketplace.mlcoin.v1.MsgBuyMallcoin\x1a-.marketplace.mlcoin.v1.MsgBuyMallcoinResponse\x12f\n" +
	"\fSellMallcoin\x12&.marketplace.mlcoin.v1.MsgSellMallcoin\x1a..marketplace.mlcoin.v1.MsgSellMallcoinResponse\x12f\n" +
	"\fMintMallcoin\x12&.marketplace.mlcoin.v1.MsgMintMallcoin\x1a..marketplace.mlcoin.v1.MsgMintMallcoinResponse\x1a\x05\x80\xe7\xb0*\x01B+Z)github.com/tmp/marketplace/x/mlcoin/typesb\x06proto3"

var (
	file_marketplace_mlcoin_v1_tx_proto_rawDescOnce sync.Once
	file_marketplace_mlcoin_v1_tx_proto_rawDescData []byte
)

func file_marketplace_mlcoin_v1_tx_proto_rawDescGZIP() []byte {
	file_marketplace_mlcoin_v1_tx_proto_rawDescOnce.Do(func() {
		file_marketplace_mlcoin_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketplace_mlcoin_v1_tx_proto_rawDesc), len(file_marketplace_mlcoin_v1_tx_proto_rawDesc)))
	})
	return file_marketplace_mlcoin_v1_tx_proto_rawDescData
}

var file_marketplace_mlcoin_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_marketplace_mlcoin_v1_tx_proto_goTypes = []any{
	(*MsgSetCurrencyRate)(nil),          // 0: marketplace.mlcoin.v1.MsgSetCurrencyRate
	(*MsgSetCurrencyRateResponse)(nil),  // 1: marketplace.mlcoin.v1.MsgSetCurrencyRateResponse
	(*MsgUpdateParams)(nil),             // 2: marketplace.mlcoin.v1.MsgUpdateParams
	(*MsgUpdateParamsResponse)(nil),     // 3: marketplace.mlcoin.v1.MsgUpdateParamsResponse
	(*MsgTransferMallcoin)(nil),         // 4: marketplace.mlcoin.v1.MsgTransferMallcoin
	(*MsgTransferMallcoinResponse)(nil), // 5: marketplace.mlcoin.v1.MsgTransferMallcoinResponse
	(*MsgBuyMallcoin)(nil),              // 6: marketplace.mlcoin.v1.MsgBuyMallcoin
	(*MsgBuyMallcoinResponse)(nil),      // 7: marketplace.mlcoin.v1.MsgBuyMallcoinResponse
	(*MsgSellMallcoin)(nil),             // 8: marketplace.mlcoin.v1.MsgSellMallcoin
	(*MsgSellMallcoinResponse)(nil),     // 9: marketplace.mlcoin.v1.MsgSellMallcoinResponse
	(*MsgMintMallcoin)(nil),             // 10: marketplace.mlcoin.v1.MsgMintMallcoin
	(*MsgMintMallcoinResponse)(nil),     // 11: marketplace.mlcoin.v1.MsgMintMallcoinResponse
	(*Params)(nil),                      // 12: marketplace.mlcoin.v1.Params
}
var file_marketplace_mlcoin_v1_tx_proto_depIdxs = []int32{
	12, // 0: marketplace.mlcoin.v1.MsgUpdateParams.params:type_name -> marketplace.mlcoin.v1.Params
	2,  // 1: marketplace.mlcoin.v1.Msg.UpdateParams:input_type -> marketplace.mlcoin.v1.MsgUpdateParams
	4,  // 2: marketplace.mlcoin.v1.Msg.TransferMallcoin:input_type -> marketplace.mlcoin.v1.MsgTransferMallcoin
	6,  // 3: marketplace.mlcoin.v1.Msg.BuyMallcoin:input_type -> marketplace.mlcoin.v1.MsgBuyMallcoin
	8,  // 4: marketplace.mlcoin.v1.Msg.SellMallcoin:input_type -> marketplace.mlcoin.v1.MsgSellMallcoin
	10, // 5: marketplace.mlcoin.v1.Msg.MintMallcoin:input_type -> marketplace.mlcoin.v1.MsgMintMallcoin
	3,  // 6: marketplace.mlcoin.v1.Msg.UpdateParams:output_type -> marketplace.mlcoin.v1.MsgUpdateParamsResponse
	5,  // 7: marketplace.mlcoin.v1.Msg.TransferMallcoin:output_type -> marketplace.mlcoin.v1.MsgTransferMallcoinResponse
	7,  // 8: marketplace.mlcoin.v1.Msg.BuyMallcoin:output_type -> marketplace.mlcoin.v1.MsgBuyMallcoinResponse
	9,  // 9: marketplace.mlcoin.v1.Msg.SellMallcoin:output_type -> marketplace.mlcoin.v1.MsgSellMallcoinResponse
	11, // 10: marketplace.mlcoin.v1.Msg.MintMallcoin:output_type -> marketplace.mlcoin.v1.MsgMintMallcoinResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_marketplace_mlcoin_v1_tx_proto_init() }
func file_marketplace_mlcoin_v1_tx_proto_init() {
	if File_marketplace_mlcoin_v1_tx_proto != nil {
		return
	}
	file_marketplace_mlcoin_v1_params_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketplace_mlcoin_v1_tx_proto_rawDesc), len(file_marketplace_mlcoin_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marketplace_mlcoin_v1_tx_proto_goTypes,
		DependencyIndexes: file_marketplace_mlcoin_v1_tx_proto_depIdxs,
		MessageInfos:      file_marketplace_mlcoin_v1_tx_proto_msgTypes,
	}.Build()
	File_marketplace_mlcoin_v1_tx_proto = out.File
	file_marketplace_mlcoin_v1_tx_proto_goTypes = nil
	file_marketplace_mlcoin_v1_tx_proto_depIdxs = nil
}
