// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: marketplace/dex/v1/genesis.proto

package types

import (
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Pool represents a liquidity pool
type Pool struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id defines the unique id of the pool.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// token_a_denom is the denomination of token A.
	TokenADenom string `protobuf:"bytes,2,opt,name=token_a_denom,json=tokenADenom,proto3" json:"token_a_denom,omitempty"`
	// token_b_denom is the denomination of token B.
	TokenBDenom string `protobuf:"bytes,3,opt,name=token_b_denom,json=tokenBDenom,proto3" json:"token_b_denom,omitempty"`
	// token_a_reserve is the current reserve of token A.
	TokenAReserve *types.Coin `protobuf:"bytes,4,opt,name=token_a_reserve,json=tokenAReserve,proto3" json:"token_a_reserve,omitempty"`
	// token_b_reserve is the current reserve of token B.
	TokenBReserve *types.Coin `protobuf:"bytes,5,opt,name=token_b_reserve,json=tokenBReserve,proto3" json:"token_b_reserve,omitempty"`
	// total_liquidity is the total liquidity tokens minted for this pool.
	TotalLiquidity *types.Coin `protobuf:"bytes,6,opt,name=total_liquidity,json=totalLiquidity,proto3" json:"total_liquidity,omitempty"`
	// fee is the swap fee (e.g., 0.003 for 0.3%).
	Fee string `protobuf:"bytes,7,opt,name=fee,proto3" json:"fee,omitempty"`
	// creator is the address that created the pool.
	Creator       string `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pool) Reset() {
	*x = Pool{}
	mi := &file_marketplace_dex_v1_genesis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pool) ProtoMessage() {}

func (x *Pool) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_dex_v1_genesis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pool.ProtoReflect.Descriptor instead.
func (*Pool) Descriptor() ([]byte, []int) {
	return file_marketplace_dex_v1_genesis_proto_rawDescGZIP(), []int{0}
}

func (x *Pool) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pool) GetTokenADenom() string {
	if x != nil {
		return x.TokenADenom
	}
	return ""
}

func (x *Pool) GetTokenBDenom() string {
	if x != nil {
		return x.TokenBDenom
	}
	return ""
}

func (x *Pool) GetTokenAReserve() *types.Coin {
	if x != nil {
		return x.TokenAReserve
	}
	return nil
}

func (x *Pool) GetTokenBReserve() *types.Coin {
	if x != nil {
		return x.TokenBReserve
	}
	return nil
}

func (x *Pool) GetTotalLiquidity() *types.Coin {
	if x != nil {
		return x.TotalLiquidity
	}
	return nil
}

func (x *Pool) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

func (x *Pool) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

// Params defines the parameters for the dex module
type Params struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// default_fee is the default swap fee for new pools.
	DefaultFee string `protobuf:"bytes,1,opt,name=default_fee,json=defaultFee,proto3" json:"default_fee,omitempty"`
	// min_liquidity is the minimum liquidity required to create a pool.
	MinLiquidity uint64 `protobuf:"varint,2,opt,name=min_liquidity,json=minLiquidity,proto3" json:"min_liquidity,omitempty"`
	// max_fee is the maximum allowed swap fee.
	MaxFee string `protobuf:"bytes,3,opt,name=max_fee,json=maxFee,proto3" json:"max_fee,omitempty"`
	// min_fee is the minimum allowed swap fee.
	MinFee        string `protobuf:"bytes,4,opt,name=min_fee,json=minFee,proto3" json:"min_fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Params) Reset() {
	*x = Params{}
	mi := &file_marketplace_dex_v1_genesis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_dex_v1_genesis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_marketplace_dex_v1_genesis_proto_rawDescGZIP(), []int{1}
}

func (x *Params) GetDefaultFee() string {
	if x != nil {
		return x.DefaultFee
	}
	return ""
}

func (x *Params) GetMinLiquidity() uint64 {
	if x != nil {
		return x.MinLiquidity
	}
	return 0
}

func (x *Params) GetMaxFee() string {
	if x != nil {
		return x.MaxFee
	}
	return ""
}

func (x *Params) GetMinFee() string {
	if x != nil {
		return x.MinFee
	}
	return ""
}

// GenesisState defines the dex module's genesis state.
type GenesisState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// params defines the parameters of the module.
	Params *Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	// pools defines all the pools present at genesis.
	Pools []*Pool `protobuf:"bytes,2,rep,name=pools,proto3" json:"pools,omitempty"`
	// next_pool_id is the next available pool ID.
	NextPoolId    uint64 `protobuf:"varint,3,opt,name=next_pool_id,json=nextPoolId,proto3" json:"next_pool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	mi := &file_marketplace_dex_v1_genesis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_dex_v1_genesis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_marketplace_dex_v1_genesis_proto_rawDescGZIP(), []int{2}
}

func (x *GenesisState) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GenesisState) GetPools() []*Pool {
	if x != nil {
		return x.Pools
	}
	return nil
}

func (x *GenesisState) GetNextPoolId() uint64 {
	if x != nil {
		return x.NextPoolId
	}
	return 0
}

var File_marketplace_dex_v1_genesis_proto protoreflect.FileDescriptor

const file_marketplace_dex_v1_genesis_proto_rawDesc = "" +
	"\n" +
	" marketplace/dex/v1/genesis.proto\x12\x12marketplace.dex.v1\x1a\x14gogoproto/gogo.proto\x1a\x1ecosmos/base/v1beta1/coin.proto\x1a\x19cosmos_proto/cosmos.proto\"\x80\x03\n" +
	"\x04Pool\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\"\n" +
	"\rtoken_a_denom\x18\x02 \x01(\tR\vtokenADenom\x12\"\n" +
	"\rtoken_b_denom\x18\x03 \x01(\tR\vtokenBDenom\x12G\n" +
	"\x0ftoken_a_reserve\x18\x04 \x01(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\rtokenAReserve\x12G\n" +
	"\x0ftoken_b_reserve\x18\x05 \x01(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\rtokenBReserve\x12H\n" +
	"\x0ftotal_liquidity\x18\x06 \x01(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\x0etotalLiquidity\x12\x10\n" +
	"\x03fee\x18\a \x01(\tR\x03fee\x122\n" +
	"\acreator\x18\b \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\acreator\"\x80\x01\n" +
	"\x06Params\x12\x1f\n" +
	"\vdefault_fee\x18\x01 \x01(\tR\n" +
	"defaultFee\x12#\n" +
	"\rmin_liquidity\x18\x02 \x01(\x04R\fminLiquidity\x12\x17\n" +
	"\amax_fee\x18\x03 \x01(\tR\x06maxFee\x12\x17\n" +
	"\amin_fee\x18\x04 \x01(\tR\x06minFee\"\xa0\x01\n" +
	"\fGenesisState\x128\n" +
	"\x06params\x18\x01 \x01(\v2\x1a.marketplace.dex.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params\x124\n" +
	"\x05pools\x18\x02 \x03(\v2\x18.marketplace.dex.v1.PoolB\x04\xc8\xde\x1f\x00R\x05pools\x12 \n" +
	"\fnext_pool_id\x18\x03 \x01(\x04R\n" +
	"nextPoolIdB\x19Z\x17marketplace/x/dex/typesb\x06proto3"

var (
	file_marketplace_dex_v1_genesis_proto_rawDescOnce sync.Once
	file_marketplace_dex_v1_genesis_proto_rawDescData []byte
)

func file_marketplace_dex_v1_genesis_proto_rawDescGZIP() []byte {
	file_marketplace_dex_v1_genesis_proto_rawDescOnce.Do(func() {
		file_marketplace_dex_v1_genesis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketplace_dex_v1_genesis_proto_rawDesc), len(file_marketplace_dex_v1_genesis_proto_rawDesc)))
	})
	return file_marketplace_dex_v1_genesis_proto_rawDescData
}

var file_marketplace_dex_v1_genesis_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_marketplace_dex_v1_genesis_proto_goTypes = []any{
	(*Pool)(nil),         // 0: marketplace.dex.v1.Pool
	(*Params)(nil),       // 1: marketplace.dex.v1.Params
	(*GenesisState)(nil), // 2: marketplace.dex.v1.GenesisState
	(*types.Coin)(nil),   // 3: cosmos.base.v1beta1.Coin
}
var file_marketplace_dex_v1_genesis_proto_depIdxs = []int32{
	3, // 0: marketplace.dex.v1.Pool.token_a_reserve:type_name -> cosmos.base.v1beta1.Coin
	3, // 1: marketplace.dex.v1.Pool.token_b_reserve:type_name -> cosmos.base.v1beta1.Coin
	3, // 2: marketplace.dex.v1.Pool.total_liquidity:type_name -> cosmos.base.v1beta1.Coin
	1, // 3: marketplace.dex.v1.GenesisState.params:type_name -> marketplace.dex.v1.Params
	0, // 4: marketplace.dex.v1.GenesisState.pools:type_name -> marketplace.dex.v1.Pool
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_marketplace_dex_v1_genesis_proto_init() }
func file_marketplace_dex_v1_genesis_proto_init() {
	if File_marketplace_dex_v1_genesis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketplace_dex_v1_genesis_proto_rawDesc), len(file_marketplace_dex_v1_genesis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_marketplace_dex_v1_genesis_proto_goTypes,
		DependencyIndexes: file_marketplace_dex_v1_genesis_proto_depIdxs,
		MessageInfos:      file_marketplace_dex_v1_genesis_proto_msgTypes,
	}.Build()
	File_marketplace_dex_v1_genesis_proto = out.File
	file_marketplace_dex_v1_genesis_proto_goTypes = nil
	file_marketplace_dex_v1_genesis_proto_depIdxs = nil
}
