upstream backend {
    server backend:4000 max_fails=3 fail_timeout=10s;
    keepalive 32;
}

upstream frontend {
    server frontend:80 max_fails=3 fail_timeout=10s;
    keepalive 32;
}

upstream chain_sentry_rpc {
    server sentry:26657 max_fails=2 fail_timeout=30s;
}
